#!/usr/bin/env python3
"""Assemble studier/story.js (chapters 1-28) from the authored specs. Chapter 1's
captions are kept as-authored; chapters 2-28 come from output/comic_specs/ch<N>.json.
Image paths are images/ch<NN>/strip<i>.jpg."""
import json
from pathlib import Path

BASE = Path(__file__).parent
SPECS = BASE / "output" / "comic_specs"

story = {}

for n in range(1, 29):
    spec = json.loads((SPECS / f"ch{n}.json").read_text())
    story[str(n)] = [{"img": f"images/ch{n:02d}/strip{i}.jpg", "cap": s["cap"]}
                     for i, s in enumerate(spec["strips"])]

header = ("// Chapter comics as REAL comic strips: each entry is one wide strip image\n"
          "// (multiple different-sized panels reading left-to-right) paired with the\n"
          "// study narration. We follow WINONA, a Native woman and warrior, across the\n"
          "// whole book. Generated by build_story.py — do not edit by hand.\n")
out = header + "window.STORY = " + json.dumps(story, indent=1, ensure_ascii=False) + ";\n"
(BASE / "studier" / "story.js").write_text(out)
print(f"Wrote story.js with {len(story)} chapters, {sum(len(v) for v in story.values())} strips.")
