#!/usr/bin/env python3
"""Assemble studier/story.js (chapters 1-28) from the authored specs. Chapter 1's
captions are kept as-authored; chapters 2-28 come from output/comic_specs/ch<N>.json.
Image paths are images/ch<NN>/strip<i>.jpg."""
import json
from pathlib import Path

BASE = Path(__file__).parent
SPECS = BASE / "output" / "comic_specs"

story = {}

# Chapters shown as cartoon-only (no text captions): the comic itself walks
# through the timeline/key events, with the date baked into each image.
NOCAP = set(range(1, 29))   # whole book is single-image, event-only, image-only

for n in range(1, 29):
    spec = json.loads((SPECS / f"ch{n}.json").read_text())
    entries = []
    for i, s in enumerate(spec["strips"]):
        e = {"img": f"images/ch{n:02d}/strip{i}.jpg"}
        if s.get("date"):
            e["date"] = s["date"]
        if n in NOCAP:
            e["nocap"] = True          # cartoon-only: no text; date is baked into the image
        else:
            e["cap"] = s["cap"]
        entries.append(e)
    story[str(n)] = entries

header = ("// Chapter comics as REAL comic strips: each entry is one wide strip image\n"
          "// (multiple different-sized panels reading left-to-right) paired with the\n"
          "// study narration. We follow WINONA, a Native woman and warrior, across the\n"
          "// whole book. Generated by build_story.py — do not edit by hand.\n")
out = header + "window.STORY = " + json.dumps(story, indent=1, ensure_ascii=False) + ";\n"
(BASE / "studier" / "story.js").write_text(out)
print(f"Wrote story.js with {len(story)} chapters, {sum(len(v) for v in story.values())} strips.")
