#!/usr/bin/env python3
"""Assemble studier/story.js (chapters 1-28) from the authored specs. Chapter 1's
captions are kept as-authored; chapters 2-28 come from output/comic_specs/ch<N>.json.
Image paths are images/ch<NN>/strip<i>.jpg."""
import json
from pathlib import Path

BASE = Path(__file__).parent
SPECS = BASE / "output" / "comic_specs"

CH1 = [
 "Long before 1492 the Americas were home to tens of millions of people in a huge variety of societies. Winona's people farmed together and held land in common — status came from generosity, not property, and many nations traced family through the mother's line. From the Aztec and Inca empires to the mounds of Cahokia, the cliffside Pueblo towns, and the Iroquois confederacy, there was no single “Indian” world.",
 "Across the ocean, Europe prized hierarchy, obedience to authority, and an established church — a very different idea of freedom. It craved Asian silk and spices and dreamed of a sea route that would cut out the Muslim and Italian middlemen. Portugal led the way: the caravel carried sailors down the African coast to island sugar plantations worked by enslaved Africans — a grim preview of New World slavery.",
 "In 1492, fresh from the Reconquista, Spain gambled on Columbus, and his landfall opened permanent contact between the hemispheres. On a Caribbean beach Winona's and Mateo's worlds finally met, with wary curiosity on both sides. The Columbian Exchange then sent crops, animals, and people both ways — corn, potatoes, and tobacco east; horses, wheat, and sugar west — remaking diets and lives worldwide.",
 "But the Exchange also carried European diseases that killed the vast majority of Native people — the worst demographic collapse in human history. With disease, steel, gunpowder, and Native allies, conquistadors like Cortés and Pizarro toppled the Aztec and Inca empires. Winona's people did not surrender quietly — resistance met conquest at every step.",
 "Spain built a vast, urban, Catholic empire on the wealth and labor of the peoples it conquered. Under the encomienda, Native laborers owed work to Spanish masters — until the friar Bartolomé de las Casas denounced the cruelty, feeding the “Black Legend” that Spain's rivals would use against it. Spanish and Native lives also blended into a new mestizo society, and missions pushed north into Florida and New Mexico.",
 "In 1680 the Pueblo Revolt drove the Spanish out of New Mexico for over a decade — the most successful Native uprising in North American history. Later, France and the Netherlands built thinly settled fur-trade colonies that, needing Native partners, left Native nations more independence than English colonies would. Two worlds were now bound together — a story that entwined new freedom for some with conquest and slavery for others.",
]

story = {}
story["1"] = [{"img": f"images/ch01/strip{i}.jpg", "cap": c} for i, c in enumerate(CH1)]

for n in range(2, 29):
    spec = json.loads((SPECS / f"ch{n}.json").read_text())
    story[str(n)] = [{"img": f"images/ch{n:02d}/strip{i}.jpg", "cap": s["cap"]}
                     for i, s in enumerate(spec["strips"])]

header = ("// Chapter comics as REAL comic strips: each entry is one wide strip image\n"
          "// (multiple different-sized panels reading left-to-right) paired with the\n"
          "// study narration. We follow WINONA, a Native woman and warrior, across the\n"
          "// whole book. Generated by build_story.py — do not edit by hand.\n")
out = header + "window.STORY = " + json.dumps(story, indent=1, ensure_ascii=False) + ";\n"
(BASE / "studier" / "story.js").write_text(out)
print(f"Wrote story.js with {len(story)} chapters, {sum(len(v) for v in story.values())} strips.")
