// Chapter comics as REAL comic strips: each entry is one wide strip image
// (multiple different-sized panels reading left-to-right) paired with the
// study narration. We follow WINONA, a Native woman and warrior, across the
// whole book. Generated by build_story.py — do not edit by hand.
window.STORY = {
 "1": [
  {
   "img": "images/ch01/strip0.jpg",
   "cap": "Long before 1492 the Americas were home to tens of millions of people in a huge variety of societies. Winona's people farmed together and held land in common — status came from generosity, not property, and many nations traced family through the mother's line. From the Aztec and Inca empires to the mounds of Cahokia, the cliffside Pueblo towns, and the Iroquois confederacy, there was no single “Indian” world."
  },
  {
   "img": "images/ch01/strip1.jpg",
   "cap": "Across the ocean, Europe prized hierarchy, obedience to authority, and an established church — a very different idea of freedom. It craved Asian silk and spices and dreamed of a sea route that would cut out the Muslim and Italian middlemen. Portugal led the way: the caravel carried sailors down the African coast to island sugar plantations worked by enslaved Africans — a grim preview of New World slavery."
  },
  {
   "img": "images/ch01/strip2.jpg",
   "cap": "In 1492, fresh from the Reconquista, Spain gambled on Columbus, and his landfall opened permanent contact between the hemispheres. On a Caribbean beach Winona's and Mateo's worlds finally met, with wary curiosity on both sides. The Columbian Exchange then sent crops, animals, and people both ways — corn, potatoes, and tobacco east; horses, wheat, and sugar west — remaking diets and lives worldwide."
  },
  {
   "img": "images/ch01/strip3.jpg",
   "cap": "But the Exchange also carried European diseases that killed the vast majority of Native people — the worst demographic collapse in human history. With disease, steel, gunpowder, and Native allies, conquistadors like Cortés and Pizarro toppled the Aztec and Inca empires. Winona's people did not surrender quietly — resistance met conquest at every step."
  },
  {
   "img": "images/ch01/strip4.jpg",
   "cap": "Spain built a vast, urban, Catholic empire on the wealth and labor of the peoples it conquered. Under the encomienda, Native laborers owed work to Spanish masters — until the friar Bartolomé de las Casas denounced the cruelty, feeding the “Black Legend” that Spain's rivals would use against it. Spanish and Native lives also blended into a new mestizo society, and missions pushed north into Florida and New Mexico."
  },
  {
   "img": "images/ch01/strip5.jpg",
   "cap": "In 1680 the Pueblo Revolt drove the Spanish out of New Mexico for over a decade — the most successful Native uprising in North American history. Later, France and the Netherlands built thinly settled fur-trade colonies that, needing Native partners, left Native nations more independence than English colonies would. Two worlds were now bound together — a story that entwined new freedom for some with conquest and slavery for others."
  }
 ],
 "2": [
  {
   "img": "images/ch02/strip0.jpg",
   "cap": "England entered the colonial race late, delayed by religious turmoil after Henry VIII and its brutal conquest of Ireland. After the failed Roanoke colony of 1585, the private Virginia Company planted Jamestown in 1607, the first permanent English settlement. Starving and sickly, the colonists survived partly by trading with Powhatan's people, whom leaders like John Smith both bargained with and threatened."
  },
  {
   "img": "images/ch02/strip1.jpg",
   "cap": "A social crisis pushed England outward: the Enclosure movement uprooted thousands of poor farmers, while promoters like Richard Hakluyt and anti-Spanish feeling urged colonization. Jamestown nearly collapsed from disease, starvation, and poor leadership until tobacco gave Virginia a profitable cash staple. The Chesapeake became a tobacco society hungry for ever more land and labor to grow it."
  },
  {
   "img": "images/ch02/strip2.jpg",
   "cap": "Reforms in 1618-1619 created the headright system, granting land for each settler brought over, and the House of Burgesses, America's first elected assembly, which met in 1619, the same year the first Africans arrived. Land was treated as the foundation of liberty, but settlers secured it by dispossessing Winona's Powhatan people rather than incorporating them, pushing steadily onto Native ground."
  },
  {
   "img": "images/ch02/strip3.jpg",
   "cap": "Relentless expansion provoked Powhatan's successor Opechancanough to strike in the Uprising of 1622, killing roughly a quarter of Virginia's settlers. Winona joined the resistance. The failed uprising doomed the Virginia Company, which lost its charter in 1624, making Virginia England's first royal colony. It also hardened English policy toward driving Indians off the land entirely."
  },
  {
   "img": "images/ch02/strip4.jpg",
   "cap": "New England developed differently. Puritans seeking to purify the Church of England migrated in family groups during the Great Migration; John Winthrop founded Massachusetts Bay in 1630. They built self-governing towns and defined 'moral liberty' as freedom to do only what was godly. Dissenters were expelled: Roger Williams founded tolerant Rhode Island, and Anne Hutchinson was tried and banished in 1637."
  },
  {
   "img": "images/ch02/strip5.jpg",
   "cap": "The Pequot War of 1637 crushed Native resistance in New England, entrenching settler supremacy. Maryland, chartered in 1632 as a Catholic refuge, passed its 1649 Toleration Act granting worship to all Christians, even as the English Civil War spread ideas about the rights of freeborn Englishmen. By 1660 freedom and unfreedom expanded together, and Winona's long fight for her people's land was only beginning."
  }
 ],
 "3": [
  {
   "img": "images/ch03/strip0.jpg",
   "cap": "By the 1670s Anglo-America was hardening around Native homelands. After England's Restoration of 1660, the crown expanded its empire on mercantilist principles, and settlement steadily eroded Indian land and autonomy. Winona's eastern woodland people, armed with bows and a few traded metal tools, watched English farms, fences, and towns press ever closer."
  },
  {
   "img": "images/ch03/strip1.jpg",
   "cap": "England organized its empire so colonial trade would enrich the mother country. Mercantilism and the Navigation Acts (from 1651) channeled goods through English ships and ports. In 1664 England seized New Netherland and renamed it New York, and after 1670 Carolina, a Barbados offshoot, built a brutal rice-and-slave economy along the southern coast."
  },
  {
   "img": "images/ch03/strip2.jpg",
   "cap": "In 1681 William Penn founded Pennsylvania as a Quaker 'holy experiment,' offering religious liberty, cheap land, and initially fair dealings with Indians. The Society of Friends promised peace, and English-Iroquois cooperation was formalized in the Covenant Chain. Yet the promise would later curdle into the fraudulent Walking Purchase of 1737 that cheated the Lenni Lenape of their land."
  },
  {
   "img": "images/ch03/strip3.jpg",
   "cap": "In King Philip's War (1675-1676), the Wampanoag leader Metacom, called King Philip, led the last great New England resistance. Winona fought beside him as villages burned on both sides. The war devastated the region but ultimately broke Indian power in New England, opening more Native land to English settlement and driving survivors to the margins."
  },
  {
   "img": "images/ch03/strip4.jpg",
   "cap": "Bacon's Rebellion (1676) burned Jamestown and exposed the danger of discontented landless former servants, pushing planters from indentured servitude toward African slavery. Lawmakers hardened racial lines: status followed the mother, conversion no longer freed slaves, and the Virginia slave code of 1705 made the colony a full slave society with race as its central divide."
  },
  {
   "img": "images/ch03/strip5.jpg",
   "cap": "The Glorious Revolution of 1688 toppled the Dominion of New England and sparked Leisler's Rebellion, while the 1692 Salem witch trials ended the old Puritan order. In the 1700s the colonies grew nearly tenfold, swelled by German, Scotch-Irish, and enslaved African migrants. Watching land and power shift, Winona passes memory and resistance to the next generation who will one day fight again."
  }
 ],
 "4": [
  {
   "img": "images/ch04/strip0.jpg",
   "cap": "By the 1750s rival European empires pressed onto Native ground in the Ohio Valley. Britain celebrated itself as the world's freest nation, yet its power grew alongside conquest and the Atlantic slave trade. For Winona's people, French and British claims meant balance-of-power diplomacy — playing one empire against another to keep their homeland."
  },
  {
   "img": "images/ch04/strip1.jpg",
   "cap": "Triangular trade routes moved manufactured goods, enslaved Africans, and plantation staples around the Atlantic. The brutal Middle Passage killed about one in five captives in transit. Olaudah Equiano, later freed, wrote a famous account of that crossing. Under 5 percent of enslaved Africans landed in mainland North America, but slavery became central to the eighteenth-century empire."
  },
  {
   "img": "images/ch04/strip2.jpg",
   "cap": "Three distinct slave systems took root: Chesapeake tobacco, South Carolina and Georgia rice and indigo worked under the task system, and smaller nonplantation slavery in the North. From many African peoples, enslaved men and women forged new African-American cultures and resisted bondage by running away and, in the 1739 Stono Rebellion, in armed revolt."
  },
  {
   "img": "images/ch04/strip3.jpg",
   "cap": "Free colonists absorbed Britain's self-image of liberty. Republicanism prized public virtue and independence; Lockean liberalism grounded government in a social contract protecting natural rights. Under salutary neglect, elected assemblies grew bold. A wide white male franchise, a booming press, the 1735 Zenger verdict, the Enlightenment, and the Great Awakening revivals of Edwards and Whitefield taught ordinary people to question authority."
  },
  {
   "img": "images/ch04/strip4.jpg",
   "cap": "Rivalry over the Ohio Valley ignited the Seven Years' War, or French and Indian War, in 1754 — the year Franklin's Albany Plan of Union was rejected. Winona's people fought beside the outnumbered French against Britain. The war soon spread worldwide, but Britain's growing strength would decide North America's fate."
  },
  {
   "img": "images/ch04/strip5.jpg",
   "cap": "The 1763 Peace of Paris expelled France from North America, stripping Indians of balance-of-power diplomacy. Inspired partly by the prophet Neolin, Pontiac's Rebellion erupted, and Britain's Proclamation of 1763 barred settlement beyond the Appalachians — angering land-hungry colonists. Winona had lost her empire ally but not her fight; wartime debts and frontier tension set the stage for the coming imperial crisis."
  }
 ],
 "5": [
  {
   "img": "images/ch05/strip0.jpg",
   "cap": "After the Seven Years' War ended in 1763, victorious Britain sat deep in debt while land-hungry colonists pushed west onto Native ground. For frontier nations like Winona's, the colonists' new cries of 'liberty' rang hollow: the same settlers demanding freedom from Parliament were eyeing the forests and hunting lands that Native peoples had held for generations."
  },
  {
   "img": "images/ch05/strip1.jpg",
   "cap": "Britain ended its hands-off approach and taxed the colonies directly. The Sugar Act (1764) tightened trade enforcement and the Stamp Act (1765) taxed printed materials. Colonists answered 'no taxation without representation,' rejecting Parliament's theory of virtual representation. The Stamp Act Congress, merchant boycotts, and the Sons of Liberty forced repeal in 1766, but the Declaratory Act insisted Parliament ruled 'in all cases whatsoever.'"
  },
  {
   "img": "images/ch05/strip2.jpg",
   "cap": "The Townshend Acts (1767) revived nonimportation, with the Daughters of Liberty weaving homespun to show colonial virtue. Troops in Boston killed five colonists in the Boston Massacre (1770), and the Tea Act sparked the Boston Tea Party (1773). Parliament's punitive Intolerable Acts (1774) backfired, uniting the colonies as the First Continental Congress organized a trade embargo enforced by local committees."
  },
  {
   "img": "images/ch05/strip3.jpg",
   "cap": "Fighting began at Lexington and Concord in April 1775. Thomas Paine's Common Sense (1776) demolished monarchy, and Congress adopted Jefferson's Declaration of Independence in July 1776, grounding the break in universal natural rights. On the frontier, Winona's people, like most Native nations, sided with the British Crown, fighting American militias to hold back the settlers who coveted their land."
  },
  {
   "img": "images/ch05/strip4.jpg",
   "cap": "Washington avoided decisive defeat and survived the Valley Forge winter after morale-saving strikes at Trenton and Princeton. Victory at Saratoga (1777) convinced France to ally in 1778, globalizing the war. Lord Dunmore's proclamation (1775) pushed thousands of enslaved people to seek freedom by fighting. After Cornwallis surrendered at Yorktown (1781), the Treaty of Paris (1783) recognized independence to the Mississippi River."
  },
  {
   "img": "images/ch05/strip5.jpg",
   "cap": "The Treaty of Paris (1783) handed the new United States land to the Mississippi, ignoring the Native nations who had fought there. Independence founded on natural rights would soon test whether 'liberty' included Winona's people. Her fight was far from over: as the young nation pressed westward, her descendants would keep defending their homeland for generations to come."
  }
 ],
 "6": [
  {
   "img": "images/ch06/strip0.jpg",
   "cap": "Independence was more than a war with Britain; it opened contests over what kind of society America would be. The Declaration's claim that all men are created equal (1776) challenged a world built on deference to rulers, masters, and husbands. Ordinary artisans, farmers, and militiamen demanded a real voice — but that promise pointedly left out Natives, the enslaved, and women."
  },
  {
   "img": "images/ch06/strip1.jpg",
   "cap": "New state constitutions turned freedom and the ballot into synonyms. Pennsylvania's radical 1776 constitution — a single-house assembly with taxpayer suffrage — dropped property qualifications, while John Adams's Thoughts on Government pushed most states toward balanced two-house legislatures. By the 1780s the vast majority of adult white men could vote in the new republic."
  },
  {
   "img": "images/ch06/strip2.jpg",
   "cap": "The Revolution transformed religion too. States disestablished official churches, and Jefferson's Virginia Bill for Establishing Religious Freedom (introduced 1779, enacted 1786) ended religious tests and public funding of worship. Disestablishment made religious liberty a defining American right — a model for rights shielded from government — even as Christian republicanism shaped public life. Winona weighs a liberty offered to some."
  },
  {
   "img": "images/ch06/strip3.jpg",
   "cap": "Economically, indentured servitude and apprenticeship faded, sharpening the line between free wage labor in the North and slavery in the South. Wartime inflation, peaking around 1780, sparked crowd actions and price-control fights — the old ideal of a community-regulated economy against Adam Smith's free-market vision in The Wealth of Nations (1776). Two visions of economic freedom outlasted the war."
  },
  {
   "img": "images/ch06/strip4.jpg",
   "cap": "Liberty had firm limits. The Treaty of Paris (1783) ignored Native land claims and opened them to settlement; roughly a fifth of free Americans were Loyalists, and some 60,000 fled amid oaths and confiscation. Enslaved people seized the moment — freedom petitions, wartime escape, and service (Lemuel Haynes). Vermont banned slavery (1777) and northern gradual abolition began, but slavery grew in the South."
  },
  {
   "img": "images/ch06/strip5.jpg",
   "cap": "Women like Abigail Adams pressed for recognition, and republican motherhood expanded female education — though coverture kept married women legally subordinate. The 1790 census counted 700,000 enslaved people, proof slavery outlasted the Revolution. The Revolution made equality a core American ideal but left Natives, the enslaved, and women outside it. Winona's fight for a place in that liberty was only beginning."
  }
 ],
 "7": [
  {
   "img": "images/ch07/strip0.jpg",
   "cap": "In 1783 an independent United States turned west toward the Ohio Valley, home to Winona's people. The war for independence was won, but the new nation was governed by the weak Articles of Confederation (ratified 1781): a one-house Congress with no president, no courts, and no power to tax or regulate trade. Its hungriest ambition lay in Native land across the Appalachians."
  },
  {
   "img": "images/ch07/strip1.jpg",
   "cap": "After states ceded their western claims, the Ordinances of 1784, 1785, and 1787 organized the public domain: land was surveyed and sold, and territories were promised entry as equal states—Jefferson's 'empire of liberty.' The Northwest Ordinance of 1787 also barred slavery north of the Ohio River. On paper the land was empty; in truth Native nations already lived there."
  },
  {
   "img": "images/ch07/strip2.jpg",
   "cap": "Postwar depression, unpayable war debts, and state paper-money schemes stirred unrest. Shays's Rebellion (1786–1787) in western Massachusetts—farmers shutting courts to stop foreclosures—terrified elites. Nationalists like James Madison and Alexander Hamilton concluded that too little government now endangered liberty and property, pushing the movement that led to the Constitutional Convention."
  },
  {
   "img": "images/ch07/strip3.jpg",
   "cap": "In Philadelphia in 1787 delegates scrapped the Articles and wrote a new Constitution. The Great Compromise fused the Virginia and New Jersey Plans into a population-based House and a state-equal Senate; federalism and checks and balances split power to prevent tyranny. Slavery shaped the bargain—the three-fifths clause, protection of the slave trade until 1808, and a fugitive slave clause—though the word never appears."
  },
  {
   "img": "images/ch07/strip4.jpg",
   "cap": "The Constitution's 'We the People' hid sharp exclusions: Indians were treated as separate nations whose land was taken by treaty and war. Winona fought with the Northwest Confederacy under Little Turtle, whose forces routed General St. Clair's army in 1791—the worst U.S. defeat by Native forces. The 1791 Bill of Rights secured liberties for citizens, but not for her people."
  },
  {
   "img": "images/ch07/strip5.jpg",
   "cap": "Little Turtle's triumph gave way to defeat at Fallen Timbers (1794) and the Treaty of Greenville (1795), which surrendered most of Ohio and Indiana for annuity payments. The Naturalization Act of 1790 reserved citizenship for 'free white persons,' and Jefferson's Notes on the State of Virginia hardened the racial line. Winona's fight for the land would pass to her descendants, whose battles were only beginning."
  }
 ],
 "8": [
  {
   "img": "images/ch08/strip0.jpg",
   "cap": "By the early 1800s the young United States pushed relentlessly west into Native homelands. While Washington's government took shape after his 1789 inauguration, settlers poured across the Appalachians onto lands nations like Winona's had held for generations. The republic's promise of liberty rarely reached the people already living on the ground it claimed."
  },
  {
   "img": "images/ch08/strip1.jpg",
   "cap": "Hamilton's financial program funded the war debt at face value, assumed state debts, chartered a national bank, taxed whiskey, and encouraged manufacturing to build a commercial republic tied to Britain. Jefferson and Madison, dreaming of an agrarian nation, became strict constructionists who saw favoritism to speculators. Their clash created the first party system: Federalists versus Republicans."
  },
  {
   "img": "images/ch08/strip2.jpg",
   "cap": "The 1794 Whiskey Rebellion and Jay's Treaty hardened the party split. Under Adams, the 1798 XYZ affair sparked a quasi-war with France, and Federalists passed the Alien and Sedition Acts, jailing Republican editors. Jefferson and Madison replied with the Virginia and Kentucky resolutions, arguing states could resist federal law—making free political expression central to American liberty."
  },
  {
   "img": "images/ch08/strip3.jpg",
   "cap": "The 'Revolution of 1800' was the first peaceful transfer of power between parties, though the three-fifths clause tipped it to Jefferson. In 1803 Marbury v. Madison established judicial review, and the Louisiana Purchase doubled the nation—forcing Jefferson to bend his constitutional scruples—while Lewis and Clark mapped the way west toward Winona's world."
  },
  {
   "img": "images/ch08/strip4.jpg",
   "cap": "Alarmed by British ties to Tecumseh and Tenskwatawa's pan-Indian confederacy, and pushed by War Hawks Clay and Calhoun, Madison led a divided nation into the War of 1812. Harrison destroyed Prophetstown at Tippecanoe in 1811. In 1814 the British burned Washington, but Fort McHenry held. Winona joined the last great pan-Native stand in the East."
  },
  {
   "img": "images/ch08/strip5.jpg",
   "cap": "Tecumseh died at the Thames, and Jackson triumphed at Horseshoe Bend and New Orleans in 1815. The Treaty of Ghent restored the status quo, yet this 'Second War of Independence' broke Indian power east of the Mississippi and discredited the Hartford Convention Federalists. As nationalism surged, Winona turned west—her people's long fight for their land far from over."
  }
 ],
 "9": [
  {
   "img": "images/ch09/strip0.jpg",
   "cap": "After the War of 1812, the Market Revolution (1800-1840) pulled American farmers and artisans out of self-sufficient local life into national and international markets. Steamboats, canals, and roads lowered the cost of moving goods and people. As settlement pushed inland, Winona's people were displaced westward, watching a new commercial world rise at the edges of their land."
  },
  {
   "img": "images/ch09/strip1.jpg",
   "cap": "Robert Fulton proved the steamboat commercially viable when the Clermont steamed the Hudson in 1807. The state-funded Erie Canal (1825) tied the Great Lakes to New York City, making it the nation's premier port, while the National Road pushed settlers across the Appalachians. Millions crossed inland and new states joined the Union, pressing onto Native land as the flag followed trade."
  },
  {
   "img": "images/ch09/strip2.jpg",
   "cap": "Eli Whitney's cotton gin (1793), fresh western land, and British textile demand built a booming Cotton Kingdom. Instead of dying out, slavery revived and expanded, fueling a huge internal slave trade that moved roughly a million enslaved people to the Deep South. The market's cotton profits enriched planters and northern merchants alike while shattering Black families."
  },
  {
   "img": "images/ch09/strip3.jpg",
   "cap": "The North industrialized differently: factories like the Lowell textile mills gathered young 'mill girls' into wage labor under one roof, part of the American system of manufactures. Mass immigration — Irish fleeing the Great Famine and German craftsmen — supplied labor but sparked nativist, anti-Catholic hostility. Marshall Court rulings like Gibbons v. Ogden (1824) and Dartmouth College v. Woodward (1819) protected commerce and contracts, letting corporations grow."
  },
  {
   "img": "images/ch09/strip4.jpg",
   "cap": "These changes remade freedom around individualism, mobility, and opportunity. Transcendentalists like Emerson and Thoreau preached self-reliance while questioning materialism; the Second Great Awakening democratized Christianity and tied moral self-discipline to market success, giving rise to new faiths like Joseph Smith's Mormonism. Belief in expansion hardened into 'manifest destiny' — a confidence that the nation was meant to spread west."
  },
  {
   "img": "images/ch09/strip5.jpg",
   "cap": "The market revolution's benefits were unevenly shared: free Black northerners faced exclusion, middle-class women were confined by the cult of domesticity, and workers battered by the Panics of 1819 and 1837 formed early unions and Workingmen's Parties. Pushed to the country's edges, Winona survives without a battle — carrying her people forward as the coming decades of expansion, and new wars, press ever westward."
  }
 ],
 "10": [
  {
   "img": "images/ch10/strip0.jpg",
   "cap": "Between the War of 1812 and 1840 political democracy for white men became the defining feature of American life; states dropped property tests until over 90 percent of adult white men could vote, and a cheap penny press fed the electorate. Alexis de Tocqueville toured in the early 1830s praising this culture of equality. Yet women, free Black men, and Winona's Cherokee were shut out."
  },
  {
   "img": "images/ch10/strip1.jpg",
   "cap": "Postwar nationalism produced Henry Clay's American System — a national bank, protective tariffs, and internal improvements — while the Monroe Doctrine (1823) warned Europe against new colonization in the Americas. Strains showed fast: the Panic of 1819 bred distrust of banks, and in McCulloch v. Maryland (1819) the Supreme Court upheld the Second Bank. This was the confident 'Era of Good Feelings.'"
  },
  {
   "img": "images/ch10/strip2.jpg",
   "cap": "The Missouri Compromise of 1820 paired Missouri with Maine and drew the 36°30' line across the Louisiana Purchase, briefly settling slavery's expansion. Later, South Carolina tried to nullify the 1828 'tariff of abominations,' and John C. Calhoun's compact theory of states' rights collided with Andrew Jackson's nationalism. The Force Act and a compromise tariff ended the nullification crisis in 1833."
  },
  {
   "img": "images/ch10/strip3.jpg",
   "cap": "Elected in 1828 through Martin Van Buren's Democratic Party machinery, Jackson signed the Indian Removal Act of 1830. The Cherokee fought back in court and won: Worcester v. Georgia (1832) recognized their sovereignty. But Jackson defied the ruling, and to the south the Seminole Wars raged as Florida's Seminoles resisted removal by force. Winona's people refused to leave quietly."
  },
  {
   "img": "images/ch10/strip4.jpg",
   "cap": "In 1838–1839 U.S. soldiers forced the Cherokee more than a thousand miles west on the Trail of Tears; thousands died of cold, hunger, and disease along the way. It was the most tragic result of the Indian Removal Act and Jackson's defiance of the courts. Winona survived the march, carrying her people's seed and memory into unfamiliar western land."
  },
  {
   "img": "images/ch10/strip5.jpg",
   "cap": "Jackson's Bank War, pet-bank deposits, and the Specie Circular helped trigger the Panic of 1837 and a long depression that sank Van Buren. By 1840 the Whigs won with William Henry Harrison's 'log cabin' campaign as turnout hit about 80 percent, and two mass parties — Democrats and Whigs — competed everywhere. Winona's democracy was built on her people's exile; her descendants would carry the fight forward."
  }
 ],
 "11": [
  {
   "img": "images/ch11/strip0.jpg",
   "cap": "By the mid-1800s Winona's people had been forced west to Indian Territory, where they rebuilt in exile. Even here she witnessed the reach of the South's 'peculiar institution.' Between 1800 and 1860 slavery became the engine of the American economy, and its shadow stretched far beyond the cotton fields themselves."
  },
  {
   "img": "images/ch11/strip1.jpg",
   "cap": "Nearly 4 million enslaved people lived in the South by 1860. Their cotton supplied about three-quarters of the world's raw cotton and over half of U.S. export earnings. Northern banks, ships, insurers, and mills all profited, making slavery a truly national system—yet the South stayed rural, dominated by a small planter elite who preached a paternalist ethos."
  },
  {
   "img": "images/ch11/strip2.jpg",
   "cap": "Congress closed the Atlantic slave trade in 1808, but an internal 'Second Middle Passage' then sold over 2 million people from the Upper South to the cotton and sugar frontier, routinely destroying families. Family separation became a defining trauma of American slavery. Winona, whose own nation had been uprooted, recognized the anguish of being torn from home."
  },
  {
   "img": "images/ch11/strip3.jpg",
   "cap": "Law defined enslaved people as property: they could not testify against whites, own guns, move freely, or (after the 1830s) legally learn to read, with discipline resting on the whip and the threat of sale. Labor ranged from cotton gang work to the rice task system. Within these bounds they built a resilient culture of family and a slave religion that read Exodus as a promise of deliverance."
  },
  {
   "img": "images/ch11/strip4.jpg",
   "cap": "Resistance ran from daily sabotage and flight—aided by the Underground Railroad and rescuers like Harriet Tubman, who escaped in 1849—to revolts: Gabriel (1800), the 1811 Louisiana rising, Denmark Vesey (1822), and Nat Turner's 1831 rebellion. The Amistad captives won freedom in 1839. After Turner, Virginia rejected emancipation in 1832 and tightened its slave codes instead."
  },
  {
   "img": "images/ch11/strip5.jpg",
   "cap": "Proslavery thinkers like George Fitzhugh recast bondage as a 'positive good,' rejecting the Declaration's promise of universal liberty even as Britain abolished slavery in 1833. The 1855 trial of Celia laid bare slaves' lack of legal personhood. Winona, a witness in exile, saw a nation split by cotton and chains—and carried forward, into her descendants, the hope that freedom was 'not forever' denied."
  }
 ],
 "12": [
  {
   "img": "images/ch12/strip0.jpg",
   "cap": "By the 1820s the Second Great Awakening taught that people were free moral agents who could remake themselves and society. This spirit of Perfectionism fueled an extraordinary wave of antebellum reform. Winona, living in the 1840s North, watches a nation convinced that sin and social ills could be eradicated, not merely managed."
  },
  {
   "img": "images/ch12/strip1.jpg",
   "cap": "Perfectionism launched the Temperance movement, begun with the American Temperance Society (1826), plus prison and asylum reform and Horace Mann's crusade for common schools, which by 1860 brought tax-supported public education to every northern state. Yet reform's Protestant moral standards angered many workers and Catholic immigrants, and Winona wonders whether its promises reach her people."
  },
  {
   "img": "images/ch12/strip2.jpg",
   "cap": "About a hundred utopian communities tested alternatives to market individualism and private property. The celibate Shakers, Robert Owen's socialist New Harmony (1825) in Indiana, and John Humphrey Noyes's Oneida (1848) experimented with cooperative property and new gender arrangements. Winona recognizes an old idea reborn: her nations, too, had long held land in common."
  },
  {
   "img": "images/ch12/strip3.jpg",
   "cap": "In the 1830s antislavery shifted from colonization to demands for immediate abolition. David Walker's Appeal (1829) and Garrison's The Liberator (1831) led the American Anti-Slavery Society (1833), spreading moral suasion through cheap print. Black abolitionists like Frederick Douglass and Sojourner Truth were central. Mobs answered with violence, murdering editor Elijah Lovejoy in 1837."
  },
  {
   "img": "images/ch12/strip4.jpg",
   "cap": "Abolitionism incubated feminism. The Grimke sisters and writers like Sarah Grimke and Margaret Fuller defended women's rights alongside the slave's. The 1848 Seneca Falls Convention, organized by Elizabeth Cady Stanton and Lucretia Mott, issued a Declaration of Sentiments demanding the vote, launching the woman suffrage movement. Winona hopes reform's widening circle might one day include her people."
  },
  {
   "img": "images/ch12/strip5.jpg",
   "cap": "In 1840 the dispute over women's roles split organized abolition, spawning the political Liberty Party, yet reformers had shattered the national silence around slavery. The gag rule (1836) even turned free speech into a bridge issue widening antislavery's appeal. Winona watches these movements grow, still waiting for their circle to widen to Native nations too."
  }
 ],
 "13": [
  {
   "img": "images/ch13/strip0.jpg",
   "cap": "By the 1840s a surge of expansion justified by manifest destiny carried the United States toward the Pacific, fusing a democratic mission with beliefs in Anglo-Saxon racial superiority. Winona now rides the 1850s Plains, watching wagon trains push through her people's buffalo hunting grounds as the nation reaches west across the continent."
  },
  {
   "img": "images/ch13/strip1.jpg",
   "cap": "American settlers in Texas broke from Mexico in 1836 after the Alamo and the Battle of San Jacinto. When the United States annexed Texas in 1845 and James K. Polk took office, it helped trigger the Mexican War (1846-1848). Victory brought the Treaty of Guadalupe Hidalgo and the vast Mexican Cession stretching to California."
  },
  {
   "img": "images/ch13/strip2.jpg",
   "cap": "The 1848 gold discovery drew a diverse flood of migrants to California, with devastating consequences for California's Indians and 'foreign' miners. The same outward push sent Commodore Perry to open Japanese ports to U.S. trade in 1854. Across the Plains, Winona skirmishes to defend her hunting grounds as the westward tide never stops."
  },
  {
   "img": "images/ch13/strip3.jpg",
   "cap": "New land forced the question of slavery's expansion into national politics. The Wilmot Proviso split Congress by section, and the 1848 Free Soil Party carried antislavery beyond abolitionists. The Compromise of 1850 briefly calmed tensions, but its harsh Fugitive Slave Act outraged northerners, forcing them to help return runaways and energizing the Underground Railroad."
  },
  {
   "img": "images/ch13/strip4.jpg",
   "cap": "Douglas's 1854 Kansas-Nebraska Act repealed the Missouri Compromise for popular sovereignty, killing the Whigs and birthing the Republican Party and its free labor ideology. Violence in 'Bleeding Kansas' and the 1856 caning of Charles Sumner deepened the divide. In 1857 the Dred Scott decision denied black citizenship and barred Congress from restricting slavery in the territories."
  },
  {
   "img": "images/ch13/strip5.jpg",
   "cap": "The 1858 Lincoln-Douglas debates made Abraham Lincoln a national voice against slavery's spread; John Brown's 1859 Harpers Ferry raid terrified the South. Lincoln's sectional 1860 win drove South Carolina and six states to form the Confederacy, and the April 1861 bombardment of Fort Sumter began the Civil War. Winona watches a house divided, sensing the fight is only widening."
  }
 ],
 "14": [
  {
   "img": "images/ch14/strip0.jpg",
   "cap": "In April 1861 the Civil War began when Confederate guns fired on Fort Sumter in Charleston harbor. The Union held huge advantages in population, industry, and finance, but had to conquer a vast, motivated South. Even as the nation split East and West, the same railroads and telegraphs pushed relentlessly onto Winona's Plains."
  },
  {
   "img": "images/ch14/strip1.jpg",
   "cap": "The First Battle of Bull Run in 1861 shattered hopes of a quick Union win. Rifled muskets, railroads, ironclads, the telegraph, and photography made this the first modern war, driving roughly 750,000 deaths. While McClellan stalled in the East, Grant seized Forts Henry and Donelson and held at Shiloh, giving the North momentum in the West."
  },
  {
   "img": "images/ch14/strip2.jpg",
   "cap": "After the bloody standoff at Antietam in September 1862, Lincoln issued the Emancipation Proclamation, effective January 1, 1863. Driven by escaping 'contrabands,' Radical Republicans, and military necessity, it made the army an agent of freedom and opened enlistment to some 200,000 black soldiers and sailors, including the famed 54th Massachusetts, reshaping debates over citizenship."
  },
  {
   "img": "images/ch14/strip3.jpg",
   "cap": "Even as the Civil War raged East, western campaigns devastated Native peoples like the Navajo and Sioux. In November 1864, U.S. cavalry attacked a peaceful Cheyenne camp in the Sand Creek Massacre, killing mostly women, children, and elders. Winona survived it. The war for one people's freedom coincided with catastrophe for another."
  },
  {
   "img": "images/ch14/strip4.jpg",
   "cap": "In July 1863 Union victories at Gettysburg and Vicksburg marked the war's turning point, splitting the Confederacy and ending Lee's northern hopes. Grant's war of attrition, plus Sherman's capture of Atlanta and March to the Sea, broke southern resistance, crippled by inflation and failed King Cotton diplomacy, and secured Lincoln's 1864 reelection."
  },
  {
   "img": "images/ch14/strip5.jpg",
   "cap": "The Thirteenth Amendment abolished slavery, and in April 1865 Lee surrendered to Grant at Appomattox Courthouse, reuniting the nation, though Lincoln was assassinated days later. This 'new birth of freedom' remade the country. Yet for Winona's people the fighting was only beginning, as the strengthened federal state now turned west toward her homeland."
  }
 ],
 "15": [
  {
   "img": "images/ch15/strip0.jpg",
   "cap": "In April 1865 the Civil War ended at Appomattox, and a victorious army turned west, opening the Plains Wars against nations like Winona's. The same nation that had just freed four million enslaved people now debated what freedom would mean during Reconstruction (1865-1877) — even as it marched into Native land."
  },
  {
   "img": "images/ch15/strip1.jpg",
   "cap": "Freedpeople defined freedom broadly: reuniting families, building churches and schools, and above all owning land — a hope raised by Sherman's Special Field Order 15 and its promise of 'forty acres and a mule.' The Freedmen's Bureau (created 1865) aided them, but when President Andrew Johnson returned confiscated land to ex-Confederates, land reform died."
  },
  {
   "img": "images/ch15/strip2.jpg",
   "cap": "With land reform dead, most freedpeople — and many poor white yeomen — were pulled into sharecropping. Under the crop-lien system, farmers borrowed against future harvests and sank into permanent debt. Meanwhile Johnson's lenient Presidential Reconstruction let ex-Confederates regain power and pass Black Codes (1865) that restricted freedpeople and mimicked slavery."
  },
  {
   "img": "images/ch15/strip3.jpg",
   "cap": "Congress seized control, passing the Civil Rights Act of 1866, the Fourteenth Amendment (birthright citizenship, equal protection), and the Reconstruction Act of 1867, which imposed military rule and Black male suffrage. Johnson was impeached in 1868 and acquitted by one vote. With the 13th, 14th, and Fifteenth Amendment (1870) barring racial voting bars, a constitutional revolution — though one excluding women — was complete."
  },
  {
   "img": "images/ch15/strip4.jpg",
   "cap": "Radical Reconstruction built America's first interracial democracy — roughly 2,000 Black officeholders, public schools, and civil rights laws. But the Ku Klux Klan waged terror, checked only briefly by the Enforcement Acts (1870-71) and the Colfax Massacre (1873). Northern will faded amid depression and Supreme Court rulings (Slaughterhouse, Cruikshank) that gutted federal protection."
  },
  {
   "img": "images/ch15/strip5.jpg",
   "cap": "The disputed 1876 Hayes-Tilden election ended in the Bargain of 1877: Hayes took the presidency, federal troops left, and Reconstruction was abandoned to the Redeemers. Winona saw two struggles fade at once — her people's land and the freedpeople's rights. Yet the 13th, 14th, and 15th Amendments endured, seeds for civil rights fights her granddaughters would still be waging."
  }
 ],
 "16": [
  {
   "img": "images/ch16/strip0.jpg",
   "cap": "By the 1870s a 'second industrial revolution' made the United States the world's leading industrial power. Railroads tripled their mileage, created a national market, and in 1883 even standardized time zones. For Winona's Plains people this Gilded Age boom, backed by federal tariffs, land grants, and troops, meant iron rails and hunters closing in on the buffalo and their homeland."
  },
  {
   "img": "images/ch16/strip1.jpg",
   "cap": "Ruthless competition drove consolidation: Carnegie built a vertically integrated steel empire and Rockefeller's Standard Oil controlled 90 percent of oil refining. Admired as 'captains of industry' or feared as 'robber barons,' such men grew immensely rich. By 1890 the richest 1 percent held as much income as the bottom half, while workers faced tenement poverty documented by Jacob Riis."
  },
  {
   "img": "images/ch16/strip2.jpg",
   "cap": "In 1876 Sioux and Cheyenne warriors destroyed Custer's command at the Battle of the Little Bighorn — the greatest Plains Indian victory. Winona and her people fought to defend their land and way of life. Yet incorporation of the West into the capitalist economy, and the deliberate extermination of the buffalo, meant even this triumph could not halt the army for long."
  },
  {
   "img": "images/ch16/strip3.jpg",
   "cap": "Capitalism remade the West: homesteaders and railroads built a wheat-and-corn empire on the Middle Border, cowboys drove cattle to Kansas railheads, and giant bonanza farms foreshadowed agribusiness. This same incorporation destroyed the Plains Indians' world. Chief Joseph's Nez Percé were forced onto reservations, and the Dawes Act of 1887 broke up tribal lands, costing Native peoples tens of millions of acres."
  },
  {
   "img": "images/ch16/strip4.jpg",
   "cap": "In 1890 the army killed Ghost Dancers at the Wounded Knee massacre, ending armed Native resistance. The Dawes Act's assault on tribal landholding, buffalo extermination, and reservations had already shattered Plains independence. For Winona this was the heartbreak after Little Bighorn — grief, endurance, and survival where an old world of freedom on the open Plains came to a close."
  },
  {
   "img": "images/ch16/strip5.jpg",
   "cap": "Gilded Age politics was corrupt and business-dominated; the Civil Service Act of 1883, Interstate Commerce Commission, and Sherman Antitrust Act set precedents but were weakly enforced. Meanwhile Social Darwinism and 'liberty of contract' fought reformers like the Knights of Labor after the 1886 Haymarket Affair. Winona endures into a new age — her people scarred but unbroken, their fight now passing to the next generation."
  }
 ],
 "17": [
  {
   "img": "images/ch17/strip0.jpg",
   "cap": "By the 1890s the frontier was declared 'closed' and federal policy aimed to erase Native life through assimilation. Reservation-era programs and boarding schools cut children's hair, forbade their languages, and forced Euro-American dress. Winona, confined and remade, keeps her dignity as the government works to dissolve her people into the nation that conquered them."
  },
  {
   "img": "images/ch17/strip1.jpg",
   "cap": "The 1890s opened with war between capital and labor. The 1892 Homestead Strike, crushed by Pinkertons and state militia, proved even strong unions could not beat giant corporations. Squeezed by falling prices, debt, and railroad rates, southern and western farmers built the Farmers' Alliance and then the People's (Populist) Party, the era's largest political insurgency."
  },
  {
   "img": "images/ch17/strip2.jpg",
   "cap": "The 1892 Omaha platform demanded a graduated income tax, direct election of senators, government control of currency, and public ownership of railroads. The 1893 depression brought Coxey's Army (1894) and the Pullman Strike (1894), both broken by federal troops and injunctions. Populists sought to curb corporate power and restore opportunity for small producers."
  },
  {
   "img": "images/ch17/strip3.jpg",
   "cap": "As Populism fell, the South hardened its racial order. From 1890 to 1906 poll taxes, literacy tests, and grandfather clauses stripped Black men of the vote, while Plessy v. Ferguson (1896) blessed segregation as 'separate but equal.' Lynching enforced it through terror, spurring Ida B. Wells's crusade; Booker T. Washington's 1895 Atlanta Compromise urged accommodation and self-help."
  },
  {
   "img": "images/ch17/strip4.jpg",
   "cap": "In 1898 the United States became an empire. The sinking of the U.S.S. Maine and Cuba's revolt sparked the Spanish-American War, and victories at Manila Bay and Santiago brought Puerto Rico, Guam, and the Philippines; Hawaii was annexed the same year. Winona's son enlists and fights for a nation still confining his own people."
  },
  {
   "img": "images/ch17/strip5.jpg",
   "cap": "The Philippine War (1899-1903) against Emilio Aguinaldo revealed the violence behind 'benevolent' empire, while the Platt Amendment (1901) and Insular Cases denied colonial subjects the constitutional rights Americans claimed as fundamental. As freedom's boundaries narrowed at home and abroad, Winona endures, and her descendants will keep fighting in the nation's wars for a century to come."
  }
 ],
 "18": [
  {
   "img": "images/ch18/strip0.jpg",
   "cap": "By 1920 more Americans lived in cities than on farms, and some 13 million immigrants, mostly from southern and eastern Europe, arrived between 1901 and 1914. Henry Ford's assembly line and 1914 five-dollar day symbolized 'Fordism,' an economy of mass production and mass consumption that tied ideas of freedom to consumer abundance and reshaped the American standard of living."
  },
  {
   "img": "images/ch18/strip1.jpg",
   "cap": "As Progressives reformed the cities, federal Indian boarding schools worked to erase Native language, dress, and culture through forced assimilation—'Kill the Indian, save the man.' Winona resists this campaign against her people even as reform swept the nation. Her fight this era is not a battle but the defense of identity, joining the first pan-Indian voices demanding dignity and self-determination."
  },
  {
   "img": "images/ch18/strip2.jpg",
   "cap": "Muckraking journalists like Upton Sinclair, whose 1906 novel The Jungle spurred the Meat Inspection and Pure Food and Drug Acts, exposed corruption, child labor, and unsafe conditions. The 1911 Triangle Shirtwaist fire killed about 146 workers trapped behind locked doors, dramatizing industrial capitalism's human cost and igniting factory-safety and labor reform across the states."
  },
  {
   "img": "images/ch18/strip3.jpg",
   "cap": "Reformers called Progressives sought to humanize industrial capitalism. Jane Addams's Hull House (1889) and other settlement houses pushed protective laws; Eugene Debs's Socialist Party peaked in 1912; and the radical IWW (1905) organized unskilled immigrants the AFL ignored. Muller v. Oregon (1908) upheld maximum-hours laws for women, while Margaret Sanger's birth-control movement linked freedom to bodily autonomy."
  },
  {
   "img": "images/ch18/strip4.jpg",
   "cap": "Theodore Roosevelt's Square Deal brought antitrust suits, railroad regulation, consumer laws, and conservation. The four-way 1912 election pitted Wilson's New Freedom against Roosevelt's New Nationalism, Taft, and Debs. Wilson won, lowering the tariff and creating the Federal Reserve (1913) and the Federal Trade Commission (1914). The Seventeenth Amendment (1913) brought direct election of senators, cementing an activist national state."
  },
  {
   "img": "images/ch18/strip5.jpg",
   "cap": "Women drove Progressive reform and revived a mass suffrage campaign, yet Progressivism also narrowed democracy through literacy tests, expert rule, and tolerance of Jim Crow. Winona's people, still fighting assimilation, joined early pan-Indian reformers demanding a place in the nation. The regulatory state forged under Roosevelt, Taft, and Wilson endured—and Winona's descendants would soon carry the struggle into America's wars."
  }
 ],
 "19": [
  {
   "img": "images/ch19/strip0.jpg",
   "cap": "When Europe went to war in 1914, President Wilson proclaimed U.S. neutrality. By April 1917 he asked Congress to make the world 'safe for democracy.' Winona's son enlists as a doughboy—many Native Americans served in World War I even though most were not yet U.S. citizens, marching off for a nation that had taken their land."
  },
  {
   "img": "images/ch19/strip1.jpg",
   "cap": "German submarine warfare turned Americans against neutrality. In 1915 a U-boat sank the Lusitania, killing 124 Americans, and in 1917 the intercepted Zimmermann Telegram revealed Germany urging Mexico to attack the U.S. Congress declared war in April 1917. Wilson framed the fight as a moral crusade rooted in his liberal internationalism."
  },
  {
   "img": "images/ch19/strip2.jpg",
   "cap": "War mobilization built a powerful temporary national state. The Selective Service Act (1917) drafted millions; the War Industries Board directed factories; high taxes and Liberty bonds paid the bills. The Committee on Public Information flooded the country with propaganda, selling the war and demanding '100 percent Americanism' from every citizen."
  },
  {
   "img": "images/ch19/strip3.jpg",
   "cap": "American troops helped turn the tide in France, fighting at the Meuse-Argonne offensive in 1918 before the armistice ended the war that November. Winona's son survives the trenches. Wilson's Fourteen Points promised self-determination, free trade, open diplomacy, and a League of Nations to prevent future wars."
  },
  {
   "img": "images/ch19/strip4.jpg",
   "cap": "Half a million Black southerners moved north in the Great Migration, meeting deadly riots in East St. Louis, Chicago, and Tulsa even as the NAACP, Du Bois, and Marcus Garvey voiced new militancy. In 1919 huge strikes and the Red Scare crushed labor and radicals. Wartime idealism also secured Prohibition and the Nineteenth Amendment (1920), giving women the vote."
  },
  {
   "img": "images/ch19/strip5.jpg",
   "cap": "At Versailles (1919) the treaty betrayed colonial hopes for self-determination, and the Senate rejected Wilson's League of Nations; voters chose Harding's 'return to normalcy' in 1920. Winona's son fought for democracy abroad while most Native Americans still lacked citizenship at home—a promise deferred. Her family's long struggle for belonging, and for full rights, was far from over."
  }
 ],
 "20": [
  {
   "img": "images/ch20/strip0.jpg",
   "cap": "The 1920s brought spectacular growth in autos, radio, and household appliances, and American firms dominated world markets. A new consumer culture—installment buying, movies, and celebrity heroes like Charles Lindbergh, who flew solo across the Atlantic in 1927—redefined freedom as private consumption, replacing thrift with credit."
  },
  {
   "img": "images/ch20/strip1.jpg",
   "cap": "The flapper symbolized a new personal freedom for women, though the proposed Equal Rights Amendment split the feminist movement. Prosperity was uneven: farmers sank into depression, unions lost over two million members under the open-shop 'American Plan,' and roughly 40 percent of Americans stayed poor. Adkins v. Children's Hospital (1923) struck down minimum-wage protection for women."
  },
  {
   "img": "images/ch20/strip2.jpg",
   "cap": "Cultural conflict defined the decade. The Sacco-Vanzetti case (arrested 1920, executed 1927) exposed deep nativist prejudice, while the revived Second Ku Klux Klan claimed millions hostile to immigrants, Catholics, and Jews. The Immigration Act of 1924 imposed national-origins quotas, slashing southern and eastern European immigration, barring Asians entirely, and inventing the category of the 'illegal alien.'"
  },
  {
   "img": "images/ch20/strip3.jpg",
   "cap": "Prohibition (in effect 1920) and the 1925 Scopes trial pitted rural Protestant fundamentalism against a secular urban modernity. In response, a modern civil-liberties movement emerged: the ACLU formed in 1920, Justices Holmes and Brandeis defended free speech after Schenck v. United States (1919), and Meyer v. Nebraska gave cultural pluralism constitutional footing."
  },
  {
   "img": "images/ch20/strip4.jpg",
   "cap": "In 1924 Congress passed the Indian Citizenship Act, finally granting United States citizenship to all Native Americans—making Winona, at last, a citizen of the country built on her homeland. The recognition was bittersweet and incomplete, arriving the same year the nativist quota law slammed the nation's doors on others, but it marked a hard-won turn in her people's long struggle."
  },
  {
   "img": "images/ch20/strip5.jpg",
   "cap": "Hoover's 1928 landslide over Al Smith seemed to ratify prosperity, but October 1929's stock market crash opened the Great Depression. By 1932 output had fallen a third and a quarter of workers were jobless; the Smoot-Hawley Tariff (1930) and belated Reconstruction Finance Corporation (1932) failed. Now a citizen, Winona faced the nation's hardest years—still standing, her long fight far from over."
  }
 ],
 "21": [
  {
   "img": "images/ch21/strip0.jpg",
   "cap": "By 1932 the Great Depression had gutted the economy—banks failed, factories closed, and a quarter of workers had no jobs. President Herbert Hoover's limited response left millions in bread lines. Winona, like most Americans, waited and hoped, as the crisis exposed how little the old federal government did for ordinary citizens."
  },
  {
   "img": "images/ch21/strip1.jpg",
   "cap": "Franklin D. Roosevelt crushed Hoover in 1932, and his first Hundred Days in 1933 unleashed unmatched legislation. He declared a bank holiday, rescued the banking system, and created federal deposit insurance. Over the radio, FDR promised a New Deal, redefining government as an active force responsible for Americans' economic security."
  },
  {
   "img": "images/ch21/strip2.jpg",
   "cap": "The First New Deal created a wave of agencies. The Civilian Conservation Corps (CCC) put jobless young men to work planting forests, the National Recovery Administration (NRA) set industry codes, and the Agricultural Adjustment Act (AAA) paid farmers to cut production. The Tennessee Valley Authority (TVA) brought flood control and cheap public electricity to a poor South."
  },
  {
   "img": "images/ch21/strip3.jpg",
   "cap": "As the Dust Bowl choked the Plains in the mid-1930s, the Second New Deal shifted from recovery to security. The Works Progress Administration (WPA) employed millions building roads, schools, and art. Programs like these gave Americans such as Winona relief and work when drought and depression had destroyed their old livelihoods."
  },
  {
   "img": "images/ch21/strip4.jpg",
   "cap": "In 1934 the Indian Reorganization Act—the 'Indian New Deal'—reversed decades of forced assimilation. It restored some tribal self-rule and land and encouraged tribal constitutions and councils. For Winona's people it was a real turn toward dignity, though reservation poverty endured. Meanwhile Social Security (1935) and the Wagner Act built a lasting welfare state."
  },
  {
   "img": "images/ch21/strip5.jpg",
   "cap": "The New Deal permanently linked American freedom to economic security through Social Security and workers' rights, forging a lasting Democratic coalition. Yet its benefits flowed unevenly, and mass unemployment lingered until World War II mobilization ended the Depression. Winona held her restored land, knowing her descendants would soon be called to fight in that coming war."
  }
 ],
 "22": [
  {
   "img": "images/ch22/strip0.jpg",
   "cap": "Through the 1930s most Americans wanted no foreign war, and the Neutrality Acts barred arms sales even as Japan invaded China and Hitler overran Europe. Roosevelt inched toward the Allies with 'cash and carry,' the Lend-Lease Act, and an oil embargo on Japan. Japan's surprise attack on Pearl Harbor on December 7, 1941, brought the United States fully into World War II."
  },
  {
   "img": "images/ch22/strip1.jpg",
   "cap": "Roosevelt framed the war's purpose around the Four Freedoms: of speech and worship, from want and fear. 'Freedom' saturated wartime culture but its meaning was contested. New Dealers pushed an Economic Bill of Rights and Congress passed the GI Bill of Rights, while business promoted 'free enterprise' and Hayek's Road to Serfdom armed postwar conservatism."
  },
  {
   "img": "images/ch22/strip2.jpg",
   "cap": "The war against Nazi racism made pluralism official rhetoric, yet tolerance had limits. Under Executive Order 9066 the government interned more than 110,000 Japanese-Americans, most of them citizens — the era's gravest violation of civil liberties. In Korematsu v. United States (1944) the Supreme Court upheld internment. The Holocaust abroad exposed racism's murderous end even as injustice persisted at home."
  },
  {
   "img": "images/ch22/strip3.jpg",
   "cap": "After early disasters the tide turned: the navy's victory at Midway in 1942 broke Japan's advance, Soviet victory at Stalingrad shattered Germany in the east, and the D-Day landings of June 1944 opened the liberation of western Europe. In the Pacific, Navajo Code Talkers — Marines transmitting in their own language — sent messages the enemy never cracked."
  },
  {
   "img": "images/ch22/strip4.jpg",
   "cap": "In 1945 US Marines fought a brutal battle for the island of Iwo Jima, and their raising of the flag atop Mount Suribachi became the war's most famous image of sacrifice. Navajo Code Talkers served through the Pacific campaigns, their unbreakable code saving countless lives — Native Americans fighting for a nation that had long denied them full rights."
  },
  {
   "img": "images/ch22/strip5.jpg",
   "cap": "Roosevelt died in April 1945 and Germany surrendered in May; after Truman ordered atomic bombs dropped on Hiroshima and Nagasaki, Japan gave up. The war ended the Depression and left the United States the dominant world power, its new order framed by Bretton Woods and the United Nations. Winona's family had fought for the Four Freedoms — and for a place in the nation they helped save."
  }
 ],
 "23": [
  {
   "img": "images/ch23/strip0.jpg",
   "cap": "World War II left only two great powers: the United States and the Soviet Union. Their wartime alliance dissolved into the Cold War, a global rivalry over the meaning of freedom. As Winona watches from her reservation in the 1950s, her family is pulled into a struggle stretching from Europe to Asia to her own tribal land."
  },
  {
   "img": "images/ch23/strip1.jpg",
   "cap": "In 1946 George Kennan's Long Telegram argued Soviet expansion must be checked, giving rise to the policy of containment, while Churchill warned an 'iron curtain' had split Europe. Containment became the foundation of postwar U.S. foreign policy, shaping every crisis to come."
  },
  {
   "img": "images/ch23/strip2.jpg",
   "cap": "The Truman Doctrine (1947) pledged to defend 'free peoples' from communism, and the Marshall Plan poured billions into rebuilding western Europe. When the Soviets blockaded Berlin in 1948, an eleven-month Allied airlift supplied the city. In 1949 the U.S. joined NATO, its first permanent European alliance, cementing containment."
  },
  {
   "img": "images/ch23/strip3.jpg",
   "cap": "After the Soviets tested an atomic bomb and Mao's communists won China in 1949, NSC-68 urged a massive arms buildup. When North Korea invaded the South in 1950, U.S.-led UN forces fought a brutal three-year Korean War. Truman fired General MacArthur in 1951; a 1953 armistice froze the stalemate near the thirty-eighth parallel."
  },
  {
   "img": "images/ch23/strip4.jpg",
   "cap": "At home, anticommunism fueled a second Red Scare. HUAC's hearings blacklisted the Hollywood Ten, and Senator Joseph McCarthy smeared thousands with unproven charges of subversion, or McCarthyism. In the same climate, the federal Termination policy tried to dissolve tribes and end their lands and status. Winona fought to keep her nation from being erased."
  },
  {
   "img": "images/ch23/strip5.jpg",
   "cap": "By 1954 televised hearings exposed McCarthy, and the Senate condemned him, yet the crusade had narrowed dissent for a generation. The Cold War hardened into a long standoff, and Termination would take years to defeat. Winona endured both fronts, her family and her nation still standing, carrying the fight forward into the decades to come."
  }
 ],
 "24": [
  {
   "img": "images/ch24/strip0.jpg",
   "cap": "In the affluent 1950s the federal Relocation program moved thousands of Native people off reservations into cities like Los Angeles, promising jobs and assimilation. Winona's family joins them, trading tribal land for a crowded urban neighborhood. The postwar boom lifted many Americans, but its promises reached Indians on very different terms."
  },
  {
   "img": "images/ch24/strip1.jpg",
   "cap": "Between 1946 and 1960 the gross national product more than doubled, and prosperity flowed into the suburbs. Mass-produced developments like Levittown, begun in 1947, were fed by the baby boom, cheap FHA and VA mortgages, and the automobile knit together by the new interstate highway system funded in 1956. Suburban family life became the new symbol of American freedom."
  },
  {
   "img": "images/ch24/strip2.jpg",
   "cap": "Television entered nine of ten homes and consumerism redefined the good life. In the 1959 kitchen debate in Moscow, Nixon told Khrushchev that American freedom meant consumer abundance and the suburban housewife. Winona sees this dream sold nightly on TV, even as her own family struggles to belong in a booming, conformist America obsessed with buying."
  },
  {
   "img": "images/ch24/strip3.jpg",
   "cap": "The decade's greatest challenge to complacency came from the Black freedom movement. In Brown v. Board of Education (1954), Thurgood Marshall convinced the Warren Court that segregated schools were inherently unequal. Rosa Parks's 1955 arrest launched the year-long Montgomery bus boycott, lifting Martin Luther King Jr. to national leadership and founding the SCLC in 1957."
  },
  {
   "img": "images/ch24/strip4.jpg",
   "cap": "White 'massive resistance,' proclaimed in the 1956 Southern Manifesto, stalled integration until Eisenhower reluctantly sent troops to Little Rock in 1957. Court victories alone could not end Jim Crow without federal enforcement. Meanwhile jobs and families streamed into the booming Sun Belt cities of the South and West, reshaping where power and growth would gather."
  },
  {
   "img": "images/ch24/strip5.jpg",
   "cap": "Postwar abundance redefined freedom as consumer choice and suburban family life, yet that dream was racially closed, and Relocation scattered Native families far from home. In the city Winona fights a quieter battle: holding her identity and passing it to her daughter. The 1950s consensus hid deep struggles that would erupt in the coming decade."
  }
 ],
 "25": [
  {
   "img": "images/ch25/strip0.jpg",
   "cap": "In February 1960, four Black college students refused to leave a whites-only lunch counter in Greensboro, North Carolina, sparking a wave of sit-ins. Young organizers formed SNCC under Ella Baker's guidance, launching a decade of grassroots activism. Watching, Winona senses the era turning as ordinary people demand their rights."
  },
  {
   "img": "images/ch25/strip1.jpg",
   "cap": "CORE's 1961 Freedom Rides tested desegregation on interstate buses. In 1963, Martin Luther King Jr.'s Birmingham campaign—met by police dogs and fire hoses broadcast worldwide—pushed Kennedy toward a civil rights bill. That August, the March on Washington drew hundreds of thousands, where King delivered his 'I Have a Dream' speech, capping the nonviolent phase."
  },
  {
   "img": "images/ch25/strip2.jpg",
   "cap": "Johnson turned the movement's momentum into law. The Civil Rights Act of 1964 banned discrimination in jobs and public places, and after Selma the Voting Rights Act of 1965 protected Black voting. His Great Society and War on Poverty built Medicare, Medicaid, Head Start, and food stamps, while the Hart-Celler Act ended racist immigration quotas."
  },
  {
   "img": "images/ch25/strip3.jpg",
   "cap": "After the 1964 Gulf of Tonkin resolution, Johnson escalated Vietnam to over half a million troops, sparking a mass antiwar movement. SDS demanded participatory democracy in the Port Huron Statement, while the counterculture and second-wave feminism—stirred by The Feminine Mystique—reshaped values. Frustration also fractured the freedom struggle: Watts, Malcolm X, and Stokely Carmichael's cry for Black Power."
  },
  {
   "img": "images/ch25/strip4.jpg",
   "cap": "The civil rights model inspired a wider rights revolution—feminism, gay liberation after the 1969 Stonewall uprising, Chavez's farm workers, environmentalism, and Native American activism. In 1969 the new Red Power movement occupied Alcatraz Island, demanding recognition of Native rights and broken treaties. Winona joins them, carrying her ancestors' long fight into a new decade."
  },
  {
   "img": "images/ch25/strip5.jpg",
   "cap": "In 1968 the Tet offensive, the assassinations of King and Robert Kennedy, and chaos at the Chicago convention climaxed the decade, and Nixon's law-and-order victory signaled liberalism's retreat. Yet America emerged freer and more open. From Alcatraz, Winona knows the struggle for justice—Black, Native, and beyond—still stretches ahead."
  }
 ],
 "26": [
  {
   "img": "images/ch26/strip0.jpg",
   "cap": "In February 1973 the American Indian Movement (AIM) occupied Wounded Knee, South Dakota, for 71 days, demanding treaty rights and self-determination. The armed standoff with federal marshals drew national attention amid the era's shattered trust in Washington. Winona's people, long ignored, forced Native rights back onto the national stage."
  },
  {
   "img": "images/ch26/strip1.jpg",
   "cap": "Richard Nixon won in 1968 on a backlash against 1960s upheaval yet governed pragmatically, creating the EPA and OSHA and broadening welfare. With Henry Kissinger he pursued 'realist' diplomacy—opening relations with communist China in 1972 and signing the SALT arms-control treaty—launching detente, an era of eased Cold War tension."
  },
  {
   "img": "images/ch26/strip2.jpg",
   "cap": "The Pentagon Papers exposed decades of official deception about Vietnam, and the 1973 Paris accords ended U.S. involvement. Nixon's obsession with enemies produced the Watergate break-in and cover-up; in August 1974 he became the first president to resign. Together Vietnam and Watergate shattered Americans' trust in the federal government, strengthening the conservative case to limit Washington's power."
  },
  {
   "img": "images/ch26/strip3.jpg",
   "cap": "The 1973 Arab oil embargo quadrupled energy prices, and 'stagflation'—stagnant growth with high inflation—defied liberal remedies. Deindustrialization sent manufacturing jobs to the low-wage Sunbelt and overseas, real wages began a long decline, and unions weakened. The postwar economic golden age was over, and hardship spread to reservations and mill towns alike."
  },
  {
   "img": "images/ch26/strip4.jpg",
   "cap": "Oil shocks and the Iran hostage crisis made Carter seem helpless, fueling a conservative coalition: neoconservatives, the evangelical Moral Majority, tax rebels behind California's Proposition 13, and Sunbelt suburbanites. Ronald Reagan harnessed it in 1980, making 'freedom' the right's rallying cry. His supply-side tax cuts and deregulation revived growth but widened inequality and tripled the national debt."
  },
  {
   "img": "images/ch26/strip5.jpg",
   "cap": "By 1988 conservatism had captured the language of freedom, yet Nixon-era self-determination policy let tribes govern their own affairs, and the first tribal-gaming court rulings opened a new road toward casino revenue and sovereignty. From the frozen standoff at Wounded Knee, Winona's people turned struggle into a future they would build themselves."
  }
 ],
 "27": [
  {
   "img": "images/ch27/strip0.jpg",
   "cap": "As Winona's generation came of age in the early 1990s, the Cold War ended: in 1989 crowds breached the Berlin Wall as communism collapsed across eastern Europe, and by 1991 the Soviet Union dissolved into fifteen nations. The United States stood as the world's lone superpower. On tribal land, the 1988 Indian Gaming Regulatory Act opened a new path toward economic self-determination."
  },
  {
   "img": "images/ch27/strip1.jpg",
   "cap": "President George H. W. Bush proclaimed a 'new world order,' intervening in Panama and leading an international coalition in the 1991 Gulf War that expelled Iraq from Kuwait. But a recession undercut his popularity. In 1992 Bill Clinton, blending social liberalism with promises to shrink government, won a three-way race in which Ross Perot took nearly a fifth of the vote."
  },
  {
   "img": "images/ch27/strip2.jpg",
   "cap": "Clinton pushed NAFTA through Congress in 1993, creating a North American free-trade zone, and expanded the Earned Income Tax Credit, though his health-care plan collapsed. Winona helped build the tribal casino authorized under gaming law—revenue that would fund schools, clinics, and the tribe's sovereignty, turning a federal opening into real self-government for her people."
  },
  {
   "img": "images/ch27/strip3.jpg",
   "cap": "In 1994 Newt Gingrich's 'Contract with America' Republicans captured Congress; Clinton recovered by declaring 'the era of big government is over,' signing the 1996 abolition of AFDC welfare. Yet the decade saw violence: the 1992 Los Angeles riots after the Rodney King verdict exposed persistent racial injustice, and Timothy McVeigh's 1995 Oklahoma City bombing killed 168, revealing antigovernment extremism."
  },
  {
   "img": "images/ch27/strip4.jpg",
   "cap": "A booming economy driven by computers, the Internet, and globalization brought low unemployment and budget surpluses, though inequality widened and the 1999 Glass-Steagall repeal loosened banking. In 1999, Battle of Seattle protesters challenged the World Trade Organization. Casino revenue let Winona's tribe open a clinic and school, funding sovereignty while the wider boom's costs sparked debate over globalization."
  },
  {
   "img": "images/ch27/strip5.jpg",
   "cap": "Culture Wars over multiculturalism and immigration reshaped the nation as Latinos became the largest minority. Clinton survived 1999 impeachment over the Lewinsky affair; in 2000 the Supreme Court's Bush v. Gore ruling handed the presidency to George W. Bush. On September 11, 2001, Al Qaeda's attacks killed some 3,000 and shattered post-Cold War security. Winona's people, self-governing at last, faced a new century."
  }
 ],
 "28": [
  {
   "img": "images/ch28/strip0.jpg",
   "cap": "A new century opened with George W. Bush in the White House, pushing huge tax cuts favoring the wealthy and rejecting the Kyoto climate treaty. From a shared homeland long ago to this quiet register, Winona's line endures into 2001. Then September 11 would redefine everything about the years ahead."
  },
  {
   "img": "images/ch28/strip1.jpg",
   "cap": "On September 11, 2001, hijacked-plane attacks killed about 3,000 people. Bush declared a global War on Terror under the Bush Doctrine—'either you are with us, or you are with the terrorists.' U.S. forces invaded Afghanistan, toppling the Taliban, and Congress passed the USA Patriot Act, vastly expanding government surveillance."
  },
  {
   "img": "images/ch28/strip2.jpg",
   "cap": "In 2003 the United States invaded Iraq without UN approval, claiming Saddam Hussein held weapons of mass destruction—claims that proved false. Baghdad fell fast, but insurgency and sectarian war followed. Detainees were held indefinitely at Guantánamo Bay, and interrogation amounting to torture stained America's reputation, reviving the old tension between security and liberty."
  },
  {
   "img": "images/ch28/strip3.jpg",
   "cap": "Hurricane Katrina flooded New Orleans in 2005; the botched federal response wrecked Bush's reputation for competence. Then years of low interest rates, subprime lending, and unregulated Wall Street speculation burst in 2008: Lehman Brothers collapsed and a $700 billion bank bailout rescued firms 'too big to fail.' The Great Recession became the worst downturn since the 1930s."
  },
  {
   "img": "images/ch28/strip4.jpg",
   "cap": "In 2008 Barack Obama was elected the first African-American president. He won a huge stimulus, the 2010 Affordable Care Act extending coverage to millions, and financial reform, and appointed Sonia Sotomayor, the first Hispanic justice. A Tea Party backlash brought gridlock; Occupy Wall Street and Black Lives Matter demanded justice, and Obergefell v. Hodges legalized same-sex marriage in 2015."
  },
  {
   "img": "images/ch28/strip5.jpg",
   "cap": "From sharing the land, to fighting for it, to fighting under America's flag, to defending tribal sovereignty—Winona's people carried through every century in this chapter's crises. In twenty-first-century America, freedom's meaning stayed contested and prosperity unevenly shared. Yet at her register in the tribal casino, Winona rings up the next customer. Still here."
  }
 ]
};
