// Chapter comics as REAL comic strips: each entry is one wide strip image
// (multiple different-sized panels reading left-to-right) paired with the
// study narration. We follow WINONA, a Native woman and warrior, across the
// whole book. Generated by build_story.py — do not edit by hand.
window.STORY = {
 "1": [
  {
   "img": "images/ch01/strip0.jpg",
   "date": "Before 1492",
   "nocap": true
  },
  {
   "img": "images/ch01/strip1.jpg",
   "date": "1434–1487",
   "nocap": true
  },
  {
   "img": "images/ch01/strip2.jpg",
   "date": "1492",
   "nocap": true
  },
  {
   "img": "images/ch01/strip3.jpg",
   "date": "After 1492",
   "nocap": true
  },
  {
   "img": "images/ch01/strip4.jpg",
   "date": "1519",
   "nocap": true
  },
  {
   "img": "images/ch01/strip5.jpg",
   "date": "1542",
   "nocap": true
  },
  {
   "img": "images/ch01/strip6.jpg",
   "date": "1608–1680",
   "nocap": true
  }
 ],
 "2": [
  {
   "img": "images/ch02/strip0.jpg",
   "date": "1585",
   "nocap": true
  },
  {
   "img": "images/ch02/strip1.jpg",
   "date": "1607",
   "nocap": true
  },
  {
   "img": "images/ch02/strip2.jpg",
   "date": "1619",
   "nocap": true
  },
  {
   "img": "images/ch02/strip3.jpg",
   "date": "1620",
   "nocap": true
  },
  {
   "img": "images/ch02/strip4.jpg",
   "date": "1622-1624",
   "nocap": true
  },
  {
   "img": "images/ch02/strip5.jpg",
   "date": "1630-1632",
   "nocap": true
  },
  {
   "img": "images/ch02/strip6.jpg",
   "date": "1636-1637",
   "nocap": true
  },
  {
   "img": "images/ch02/strip7.jpg",
   "date": "1649-1662",
   "nocap": true
  }
 ],
 "3": [
  {
   "img": "images/ch03/strip0.jpg",
   "date": "1651-1660",
   "nocap": true
  },
  {
   "img": "images/ch03/strip1.jpg",
   "date": "1664-1670",
   "nocap": true
  },
  {
   "img": "images/ch03/strip2.jpg",
   "date": "1675-1676",
   "nocap": true
  },
  {
   "img": "images/ch03/strip3.jpg",
   "date": "1676-1681",
   "nocap": true
  },
  {
   "img": "images/ch03/strip4.jpg",
   "date": "1686-1688",
   "nocap": true
  },
  {
   "img": "images/ch03/strip5.jpg",
   "date": "1689",
   "nocap": true
  },
  {
   "img": "images/ch03/strip6.jpg",
   "date": "1692-1705",
   "nocap": true
  },
  {
   "img": "images/ch03/strip7.jpg",
   "date": "1737-1750",
   "nocap": true
  }
 ],
 "4": [
  {
   "img": "images/ch04/strip0.jpg",
   "date": "1707",
   "nocap": true
  },
  {
   "img": "images/ch04/strip1.jpg",
   "date": "1712",
   "nocap": true
  },
  {
   "img": "images/ch04/strip2.jpg",
   "date": "1718–1732",
   "nocap": true
  },
  {
   "img": "images/ch04/strip3.jpg",
   "date": "1735–1739",
   "nocap": true
  },
  {
   "img": "images/ch04/strip4.jpg",
   "date": "1741",
   "nocap": true
  },
  {
   "img": "images/ch04/strip5.jpg",
   "date": "1707–1750",
   "nocap": true
  },
  {
   "img": "images/ch04/strip6.jpg",
   "date": "1754–1756",
   "nocap": true
  },
  {
   "img": "images/ch04/strip7.jpg",
   "date": "1763",
   "nocap": true
  },
  {
   "img": "images/ch04/strip8.jpg",
   "date": "1764–1769",
   "nocap": true
  }
 ],
 "5": [
  {
   "img": "images/ch05/strip0.jpg",
   "date": "1764–1765",
   "cap": "After the Seven Years' War, Parliament taxed the colonies. The **Sugar Act** of **1764** tightened trade enforcement, and the **Stamp Act** of **1765** placed the first direct tax on printed goods. Colonists cried 'no taxation without representation,' rejecting **virtual representation**, and the **Stamp Act Congress** met to organize resistance."
  },
  {
   "img": "images/ch05/strip1.jpg",
   "date": "1765–1766",
   "cap": "The **Sons of Liberty** led mobs—gutting Thomas Hutchinson's Boston mansion—while **Committees of Correspondence** linked towns. Boycotts forced repeal of the **Stamp Act** in **1766**, but the **Declaratory Act** insisted Parliament could still legislate for America 'in all cases whatsoever.'"
  },
  {
   "img": "images/ch05/strip2.jpg",
   "date": "1767",
   "cap": "The **Townshend Acts** of **1767** imposed new duties on imports like glass and tea. Colonists revived nonimportation, and the Daughters of Liberty made homespun cloth a badge of colonial virtue, pressuring Britain through organized boycotts."
  },
  {
   "img": "images/ch05/strip3.jpg",
   "date": "1770–1773",
   "cap": "Soldiers stationed in Boston fired on locals in the **Boston Massacre** of **1770**, killing five colonists. When Parliament passed the Tea Act, colonists staged the **Boston Tea Party** in **1773**, dumping British tea into the harbor to protest taxation."
  },
  {
   "img": "images/ch05/strip4.jpg",
   "date": "1774",
   "cap": "Parliament's punitive **Intolerable Acts** of **1774** closed Boston's port and punished Massachusetts. Rather than isolating the colony, they united America: the First **Continental Congress** met in Philadelphia and organized a trade embargo enforced by local committees, drawing ordinary farmers and artisans into politics."
  },
  {
   "img": "images/ch05/strip5.jpg",
   "date": "1775",
   "cap": "War began at the **Battles of Lexington and Concord** in April **1775**. That same year, **Lord Dunmore's proclamation** offered freedom to enslaved people who fought for Britain, and thousands sought liberty by serving one side or the other during the coming war."
  },
  {
   "img": "images/ch05/strip6.jpg",
   "date": "1776",
   "cap": "Thomas Paine's **Common Sense** of **1776** demolished the case for monarchy in plain language. Months later, Congress adopted Jefferson's **Declaration of Independence** in **1776**, grounding the break with Britain in universal natural rights rather than merely the rights of Englishmen."
  },
  {
   "img": "images/ch05/strip7.jpg",
   "date": "1777–1778",
   "cap": "Washington kept his army alive through the Valley Forge winter after strikes at Trenton and Princeton. The American victory at the **Battle of Saratoga** in **1777** became the war's turning point, convincing France to ally with the United States in **1778** and globalizing the conflict."
  },
  {
   "img": "images/ch05/strip8.jpg",
   "date": "1781–1783",
   "cap": "After Cornwallis surrendered at Yorktown in **1781**, Britain's war effort collapsed. The **Treaty of Paris** of **1783** recognized American independence, with borders stretching all the way to the Mississippi River, securing the new United States."
  }
 ],
 "6": [
  {
   "img": "images/ch06/strip0.jpg",
   "date": "1700",
   "cap": "In **1700**, Boston judge **Samuel Sewall** published **The Selling of Joseph**, America's first antislavery tract, planting an early seed of doubt about bondage. Decades before independence, it foreshadowed how the coming revolution would force the new **Republic** to ask whether liberty could coexist with slavery."
  },
  {
   "img": "images/ch06/strip1.jpg",
   "date": "1773",
   "cap": "Beginning in **1773**, enslaved New Englanders turned the Revolution's language back on their enslavers, submitting **freedom petitions** to courts and legislatures demanding liberty. These petitions argued that natural rights belonged to all, exposing the gap between patriot ideals and the reality of slavery."
  },
  {
   "img": "images/ch06/strip2.jpg",
   "date": "1776",
   "cap": "In **1776** Pennsylvania adopted the radical **Pennsylvania Constitution of 1776**, with a single-house assembly and taxpayer **suffrage** that widened who could vote in the new **Republic**. That year John Adams's **Thoughts on Government** pushed most states toward balanced two-house legislatures, while Adam Smith's **The Wealth of Nations** offered a free-market vision challenging community-regulated economies."
  },
  {
   "img": "images/ch06/strip3.jpg",
   "date": "1777",
   "cap": "In **1777** Vermont's constitution became the first to ban slavery outright, turning revolutionary ideals into law. It signaled that some Americans would push beyond scattered **freedom petitions** toward abolishing bondage entirely, even as slavery survived elsewhere."
  },
  {
   "img": "images/ch06/strip4.jpg",
   "date": "1779",
   "cap": "In **1779** Jefferson introduced his **Bill for Establishing Religious Freedom**, pressing for **disestablishment** by ending official churches, religious tests, and public funding of worship. The same year, Clinton's Philipsburg Proclamation offered refuge to escaped slaves who fled to British lines. The Revolution reshaped faith into **Christian republicanism**, prizing virtue while shielding conscience from government."
  },
  {
   "img": "images/ch06/strip5.jpg",
   "date": "1780",
   "cap": "By **1780**, wartime inflation peaked and Continental money collapsed in value. Crowds staged actions and demanded price controls, pitting the older ideal of a community-regulated economy against the free-market vision of **The Wealth of Nations**. These clashes deepened the divide as **free labor** slowly replaced servitude in the North."
  },
  {
   "img": "images/ch06/strip6.jpg",
   "date": "1782",
   "cap": "In **1782** Deborah Sampson enlisted in the Continental army disguised as a man, defying the limits placed on women. Though **coverture** kept married women legally subordinate to their husbands, the Revolution birthed **republican motherhood**, honoring women who raised virtuous citizens and expanding female education."
  },
  {
   "img": "images/ch06/strip7.jpg",
   "date": "1783",
   "cap": "The **1783** Treaty of Paris ended the war but ignored Indian land claims, opening Native homelands to settlement whether tribes had allied with Britain or the patriots; Winona watches her people dispossessed. The treaty also required an end to persecution of **Loyalists**, about a fifth of free Americans, though many still faced oaths, confiscation, and exile, with some 60,000 leaving the country."
  },
  {
   "img": "images/ch06/strip8.jpg",
   "date": "1786",
   "cap": "In **1786** Virginia enacted Jefferson's **Bill for Establishing Religious Freedom**, completing **disestablishment** and making religious liberty the model for rights shielded from government. Amid these currents a **free black** community grew, and **Lemuel Haynes** became a celebrated Black minister to white congregations, embodying the era's expanding liberty."
  },
  {
   "img": "images/ch06/strip9.jpg",
   "date": "1790–1804",
   "cap": "The first census of **1790** counted 700,000 enslaved people, proving slavery grew despite the Revolution, even as Northern **free labor** displaced servitude. Northern states enacted **gradual abolition**, and in **1804** New Jersey became the last to do so, while slavery entrenched in the South, showing how limited the era's liberty truly was."
  }
 ],
 "7": [
  {
   "img": "images/ch07/strip0.jpg",
   "date": "1781",
   "cap": "The **Articles of Confederation**, ratified in **1781** after states ceded their western land claims, built a deliberately weak union: a one-house Congress with no president, no courts, and no power to tax or regulate trade. This frail government could barely pay its war debts, leaving national authority dependent on the goodwill of the states."
  },
  {
   "img": "images/ch07/strip1.jpg",
   "date": "1784–1785",
   "cap": "In the West the Confederation scored a lasting win. Jefferson's ordinance of **1784** promised territories would enter as equal states, his **empire of liberty**, and the Land Ordinance of **1785** set up the survey and sale of the public domain across the Old Northwest. Ordered grids replaced chaos, turning wilderness into future states of the Union."
  },
  {
   "img": "images/ch07/strip2.jpg",
   "date": "1786–1787",
   "cap": "Postwar depression, unpayable debts, and state paper-money schemes exploded into **Shays's Rebellion (1786–1787)** in western Massachusetts, while the Annapolis meeting of **1786** called for reform. To nationalists like Madison and Hamilton, the uprising proved that too little government now threatened liberty itself, and that the Articles had to be scrapped."
  },
  {
   "img": "images/ch07/strip3.jpg",
   "date": "1787",
   "cap": "In **1787** the **Constitutional Convention** scrapped the Articles. The Great Compromise fused the **Virginia Plan** and the **New Jersey Plan** into a population-based House and a state-equal Senate, while **federalism** and **checks and balances** divided power to prevent tyranny. That same year the **Northwest Ordinance of 1787** organized the territories and barred slavery north of the Ohio River."
  },
  {
   "img": "images/ch07/strip4.jpg",
   "date": "1787–1788",
   "cap": "Slavery shaped the bargain: the **three-fifths clause** inflated southern power, the slave trade was shielded, and a fugitive clause reached across state lines. Defending the plan, **The Federalist** essays—published from **1788**—rallied commercial support, while **Anti-Federalists** feared distant, aristocratic rule. In **1788** the ninth state ratified, putting the Constitution into effect."
  },
  {
   "img": "images/ch07/strip5.jpg",
   "date": "1790",
   "cap": "The first census of **1790** counted 3.9 million Americans, but 'We the People' hid sharp exclusions. The **Naturalization Act of 1790** limited citizenship by immigration to 'free white persons.' Jefferson's **Notes on the State of Virginia** lent intellectual cover to a hardening racial line, helping make race the chief justification for slavery in a nation dedicated to freedom."
  },
  {
   "img": "images/ch07/strip6.jpg",
   "date": "1791",
   "cap": "In the East, the promised **Bill of Rights** was ratified in **1791**, sealing Federalist victory. That same year in the Ohio Valley, the Miami leader **Little Turtle** routed **St. Clair's army**—the worst defeat the U.S. Army ever suffered against Native nations—as Indians defended homelands the Constitution treated as separate territory to be taken by treaty and war."
  },
  {
   "img": "images/ch07/strip7.jpg",
   "date": "1794–1795",
   "cap": "American forces won the **Battle of Fallen Timbers** in **1794**, breaking Native resistance. The **Treaty of Greenville (1795)** then transferred most of Ohio and Indiana to the United States through land cessions and an annuity system. Finally, in **1808**, Congress banned the importation of slaves at the earliest moment the Constitution permitted."
  }
 ],
 "8": [
  {
   "img": "images/ch08/strip0.jpg",
   "date": "1789–1791",
   "nocap": true
  },
  {
   "img": "images/ch08/strip1.jpg",
   "date": "1791–1804",
   "nocap": true
  },
  {
   "img": "images/ch08/strip2.jpg",
   "date": "1794",
   "nocap": true
  },
  {
   "img": "images/ch08/strip3.jpg",
   "date": "1798",
   "nocap": true
  },
  {
   "img": "images/ch08/strip4.jpg",
   "date": "1800–1803",
   "nocap": true
  },
  {
   "img": "images/ch08/strip5.jpg",
   "date": "1804–1807",
   "nocap": true
  },
  {
   "img": "images/ch08/strip6.jpg",
   "date": "1811–1813",
   "nocap": true
  },
  {
   "img": "images/ch08/strip7.jpg",
   "date": "1814–1815",
   "nocap": true
  }
 ],
 "9": [
  {
   "img": "images/ch09/strip0.jpg",
   "date": "1793",
   "cap": "In **1793** **Eli Whitney** built the **cotton gin**, which cheaply separated seeds from fiber and made short-staple cotton wildly profitable. This single invention launched the **Cotton Kingdom** across the Deep South, reviving slavery and driving planters to seize ever more western land and enslaved labor."
  },
  {
   "img": "images/ch09/strip1.jpg",
   "date": "1806-1807",
   "cap": "In **1806** Congress funded the **National Road** from Cumberland, Maryland toward the Old Northwest, while in **1807** **Robert Fulton**'s Clermont steamed up the Hudson, proving steamboats viable. These transport breakthroughs kicked off the **Market revolution**, pulling once self-sufficient farmers into distant national and international markets."
  },
  {
   "img": "images/ch09/strip2.jpg",
   "date": "1814",
   "cap": "In **1814** the Boston Associates opened their **Waltham**, Massachusetts factory, combining every stage of cloth production under one roof. This pioneering **American system of manufactures** used interchangeable parts and integrated machinery, moving Northern craft work out of homes and into large water-powered mills."
  },
  {
   "img": "images/ch09/strip3.jpg",
   "date": "1819",
   "cap": "In **1819** the Marshall Court's **Dartmouth College v. Woodward** ruled a corporate charter a binding contract, shielding businesses from state interference. The same year the **Adams-Onis Treaty** transferred Florida from Spain, and the **Panic of 1819** — the young nation's first great depression — threw farmers and workers into crisis."
  },
  {
   "img": "images/ch09/strip4.jpg",
   "date": "1824-1825",
   "cap": "In **1824** **Gibbons v. Ogden** struck down a steamboat monopoly, affirming federal power over interstate commerce. Then in **1825** the state-funded **Erie Canal** opened, linking the Great Lakes to New York City, slashing shipping costs and making New York the nation's premier port and commercial capital."
  },
  {
   "img": "images/ch09/strip5.jpg",
   "date": "1831-1837",
   "cap": "The Lowell textile mills employed young **mill girls**, bringing wage labor and independence to farm daughters. On the land, Cyrus McCormick's mechanical reaper (**1831**) and John Deere's steel plow (**1837**) multiplied harvests — even as the **Panic of 1837** launched a brutal depression, deepening the **Market revolution**."
  },
  {
   "img": "images/ch09/strip6.jpg",
   "date": "1830s-1840s",
   "cap": "The **Second Great Awakening** democratized Christianity, tying moral self-discipline to market success and birthing new faiths — including **Joseph Smith and the Mormons**. Reacting against materialism, **Transcendentalists** like Emerson and Thoreau preached self-reliance, individualism, and communion with nature over money."
  },
  {
   "img": "images/ch09/strip7.jpg",
   "date": "1844-1845",
   "cap": "In **1844** Samuel Morse's telegraph entered commercial service, enabling instant long-distance communication. In **1845** editor John O'Sullivan coined **Manifest destiny**, the belief that Americans were divinely fated to expand across the continent — a conviction that justified settlement pushing ever westward."
  },
  {
   "img": "images/ch09/strip8.jpg",
   "date": "1845-1854",
   "cap": "The **Great Famine** of **1845-1851** drove roughly a million Irish, plus German craftsmen, to the U.S., fueling **Nativism** — hostility toward Catholic immigrants. Meanwhile the **Cult of domesticity** confined middle-class women to the home, and workers demanded a **Family wage**. In **1854** Thoreau published Walden, condemning market society's values."
  }
 ],
 "10": [
  {
   "img": "images/ch10/strip0.jpg",
   "date": "1816–1819",
   "cap": "Postwar nationalism fueled Henry Clay's **American System** — a national bank, protective tariffs, and internal improvements — amid the one-party calm dubbed the **Era of Good Feelings**. Congress chartered the Second Bank and passed the first protective tariff in **1816**. Then reckless speculation burst in the **Panic of 1819**, breeding lasting distrust of banks."
  },
  {
   "img": "images/ch10/strip1.jpg",
   "date": "1819–1820",
   "cap": "In **McCulloch v. Maryland** (**1819**), Marshall upheld the national bank and denied states power to tax it. Slavery's expansion then split Congress until the **Missouri Compromise** of **1820** admitted Missouri as slave and Maine as free, banning slavery north of 36°30′ across the Louisiana Purchase."
  },
  {
   "img": "images/ch10/strip2.jpg",
   "date": "1823–1825",
   "cap": "The **Monroe Doctrine** of **1823** warned Europe against new colonization in the Americas. After the four-way **1824** election, the House in **1825** chose John Quincy Adams; when he named Clay secretary of state, Jackson's backers cried **corrupt bargain**, poisoning politics before the next contest."
  },
  {
   "img": "images/ch10/strip3.jpg",
   "date": "1828",
   "cap": "Congress passed the high **tariff of abominations** in **1828**, enraging the South, while Andrew Jackson won the presidency through Martin Van Buren's new Democratic machinery. Jackson rewarded loyal supporters with government jobs — the **spoils system** — casting rotation in office as democratic reform for the common white man."
  },
  {
   "img": "images/ch10/strip4.jpg",
   "date": "1830",
   "cap": "The **Indian Removal Act** became law in **1830**, empowering Jackson to force southeastern nations — including Winona's Cherokee — off their homelands. The same year, the **Webster-Hayne debate** aired nullification arguments in the Senate, pitting states' rights against Daniel Webster's ringing defense of the Union."
  },
  {
   "img": "images/ch10/strip5.jpg",
   "date": "1832",
   "cap": "In **Worcester v. Georgia** (**1832**) the Court ruled Georgia could not seize Cherokee land, but Jackson ignored it. That year he vetoed the bank recharter — opening the **Bank War** — and won reelection, while South Carolina nullified the tariff. **John C. Calhoun's** compact theory drove the deepening **nullification crisis**."
  },
  {
   "img": "images/ch10/strip6.jpg",
   "date": "1833–1837",
   "cap": "The **Force Act** and a compromise tariff ended the **nullification crisis** in **1833**. Jackson's **Bank War** — shifting deposits to pet banks and issuing the Specie Circular — destabilized credit. The resulting **Panic of 1837** began a long depression that crushed Martin Van Buren's presidency."
  },
  {
   "img": "images/ch10/strip7.jpg",
   "date": "1838–1839",
   "cap": "Enforcing removal, the U.S. Army drove the Cherokee — Winona's people — over a thousand miles west on the **Trail of Tears** in **1838–1839**. Thousands died of cold, hunger, and disease along the way, defying the **Worcester v. Georgia** ruling and marking the era's cruelest contradiction of its democratic self-image."
  },
  {
   "img": "images/ch10/strip8.jpg",
   "date": "1840",
   "cap": "In **1840** the Whigs won with the 'log cabin' campaign for William Henry Harrison, and turnout hit about 80 percent. Two organized national parties now competed everywhere, borrowing the marketplace's selling techniques — the mature mass politics Alexis de Tocqueville had watched take root in Jacksonian America."
  }
 ],
 "11": [
  {
   "img": "images/ch11/strip0.jpg",
   "date": "1791–1804",
   "cap": "From **1791 to 1804** the **Haitian Revolution** overthrew slavery in Saint-Domingue, creating the first Black republic. Its victory kindled hope among enslaved Americans and terror among masters, who feared their own **peculiar institution** might burn the same way, hardening Southern vigilance against any hint of revolt."
  },
  {
   "img": "images/ch11/strip1.jpg",
   "date": "1800",
   "cap": "In **1800**, inspired by Haiti, the Virginia blacksmith Gabriel planned a large slave rebellion around Richmond, but a storm and informers doomed it — **Gabriel's plot** was uncovered and its leaders hanged. Such **fugitive slaves** and rebels revealed the resistance simmering constantly beneath the surface of Southern bondage."
  },
  {
   "img": "images/ch11/strip2.jpg",
   "date": "1808",
   "cap": "When Congress banned the Atlantic slave trade in **1808**, demand shifted inland, launching the **Second Middle Passage** — over two million people sold from the Upper South to the cotton and sugar frontier by 1860. This forced internal trade routinely shattered enslaved families for profit."
  },
  {
   "img": "images/ch11/strip3.jpg",
   "date": "1811",
   "cap": "In **1811** enslaved workers on the Louisiana sugar coast staged the era's largest revolt, marching hundreds strong toward New Orleans before troops crushed them. Sugar and cotton fed the boast that **Cotton Is King**: Southern cotton supplied three-quarters of the world's raw supply and over half of U.S. export earnings."
  },
  {
   "img": "images/ch11/strip4.jpg",
   "date": "1822",
   "cap": "In **1822** authorities uncovered **Denmark Vesey's conspiracy**, a planned Charleston uprising led by a free carpenter. Betrayed before it began, Vesey and dozens were executed. **Slave religion**, which read the Exodus story as God's promise of deliverance and judged slavery a sin, terrified whites, who blamed Black churches and cracked down hard."
  },
  {
   "img": "images/ch11/strip5.jpg",
   "date": "1831",
   "cap": "In **1831** **Nat Turner's Rebellion** killed about sixty whites in Virginia before being crushed, sending shockwaves through the South. That same year of **1831**, Garrison launched *The Liberator*, demanding immediate abolition. Both events pushed the region toward a defensive, aggressive stance on slavery."
  },
  {
   "img": "images/ch11/strip6.jpg",
   "date": "1832–1833",
   "cap": "In **1832** Virginia debated but rejected gradual emancipation, tightening its slave codes instead. When Great Britain abolished slavery empire-wide in **1833**, the South stood isolated in a world turning against bondage. Most Southern whites were **plain folk** — the three-quarters of families who owned no slaves yet still defended the system."
  },
  {
   "img": "images/ch11/strip7.jpg",
   "date": "1838–1839",
   "cap": "In **1838** Frederick Douglass escaped slavery in Maryland to become a leading abolitionist. In **1839** African captives seized **the Amistad**; the Supreme Court later freed them. Most enslaved people, though, endured **gang labor** in cotton under overseers or the **task system** on rice plantations, driven by the whip."
  },
  {
   "img": "images/ch11/strip8.jpg",
   "date": "1849–1855",
   "cap": "In **1849** **Harriet Tubman** escaped to Philadelphia, then guided others north via the **Underground Railroad**. Planters justified bondage through **paternalism** and a **proslavery argument** — thinker **George Fitzhugh** claimed white freedom required Black slavery. In **1855** the trial and execution of **Celia**, who killed a rapist master, exposed slaves' utter lack of legal personhood."
  }
 ],
 "12": [
  {
   "img": "images/ch12/strip0.jpg",
   "date": "1816",
   "cap": "Revivalism spread **Perfectionism**, the faith that people and society could be remade, sparking an age of reform. In **1816** reformers founded the **American Colonization Society**, backing gradual emancipation and resettlement of free Black Americans in Africa—a plan many Black families rejected as exile from the only country they had ever known."
  },
  {
   "img": "images/ch12/strip1.jpg",
   "date": "1825–1826",
   "cap": "Roughly a hundred **utopian communities** tested new ways of living: the celibate **Shakers** worshiped through ecstatic dance, and in **1825** Robert Owen built the socialist **New Harmony** in Indiana. In **1826** the American Temperance Society launched the **temperance movement**, the era's largest crusade, urging Americans to swear off alcohol entirely."
  },
  {
   "img": "images/ch12/strip2.jpg",
   "date": "1827–1829",
   "cap": "Horace Mann's **common schools** brought tax-supported public education, reaching every northern state by **1860**. In **1827** *Freedom's Journal*, the first Black newspaper, began publishing; then in **1829** **David Walker's Appeal** to the Coloured Citizens of the World shocked the nation by calling on enslaved people to resist slavery directly."
  },
  {
   "img": "images/ch12/strip3.jpg",
   "date": "1831–1833",
   "cap": "In **1831** **William Lloyd Garrison** launched *The Liberator*, demanding immediate abolition and equal citizenship. Two years later, in **1833**, activists founded the **American Anti-Slavery Society** in Philadelphia, which grew to about 100,000 members. It fought slavery through **moral suasion**—flooding the country with cheap print and revival-style oratory to change hearts and minds."
  },
  {
   "img": "images/ch12/strip4.jpg",
   "date": "1836–1837",
   "cap": "In **1836** the House adopted the **gag rule**, automatically tabling antislavery petitions and convincing many northerners that slavery menaced white liberties too. The **Grimke sisters**, attacked for speaking publicly, defended women's rights alongside the slave's. In **1837** a mob murdered abolitionist editor Elijah Lovejoy at Alton, Illinois, making him an antislavery martyr."
  },
  {
   "img": "images/ch12/strip5.jpg",
   "date": "1840",
   "cap": "In **1840** organized abolitionism split over women's public roles. One wing turned to politics and formed the **Liberty Party**, nominating James G. Birney for president to fight slavery at the ballot box. The clash pushed women reformers toward defending their own rights, planting the seeds of an organized women's movement."
  },
  {
   "img": "images/ch12/strip6.jpg",
   "date": "1848",
   "cap": "The **1848** **Seneca Falls Convention**, organized by Elizabeth Cady Stanton and Lucretia Mott, issued a Declaration of Sentiments demanding the vote and full equality, launching the woman suffrage movement. That same year John Humphrey Noyes founded the **Oneida** community in New York, one of the boldest **utopian communities**, experimenting with shared property and radical new gender arrangements."
  },
  {
   "img": "images/ch12/strip7.jpg",
   "date": "1852",
   "cap": "In **1852** Frederick Douglass delivered 'What, to the Slave, Is the Fourth of July?', exposing the hypocrisy of a nation that celebrated liberty while holding millions in bondage. The same year Harriet Beecher Stowe's *Uncle Tom's Cabin* became a runaway bestseller, turning countless northern readers against slavery and hardening the sectional divide."
  }
 ],
 "13": [
  {
   "img": "images/ch13/strip0.jpg",
   "date": "1836",
   "cap": "In **1836** the **Texas Revolt** ended when Anglo settlers, having lost the Alamo, won independence from Mexico at the **Battle of San Jacinto**. This new Republic of Texas set the stage for a decade of aggressive expansion driven by the belief in **manifest destiny**."
  },
  {
   "img": "images/ch13/strip1.jpg",
   "date": "1845",
   "cap": "Fired by **manifest destiny** and a racial vision of Anglo-Saxon superiority, the United States annexed Texas in **1845** as **James K. Polk** became president. Annexation of the vast slaveholding republic pushed the nation toward war with Mexico."
  },
  {
   "img": "images/ch13/strip2.jpg",
   "date": "1846",
   "cap": "The **Mexican War** began in **1846**, opening a continental conquest. That same year **David Wilmot** proposed the **Wilmot Proviso** to ban slavery in any land won from Mexico. It failed, but it split Congress along sectional lines rather than party lines."
  },
  {
   "img": "images/ch13/strip3.jpg",
   "date": "1848",
   "cap": "In **1848** the **Treaty of Guadalupe Hidalgo** ended the **Mexican War** and handed the U.S. the huge **Mexican Cession**. Gold discovered in California sparked the **Gold rush**, drawing diverse migrants and devastating California's Indians. The new **Free Soil Party** carried antislavery politics beyond the abolitionists."
  },
  {
   "img": "images/ch13/strip4.jpg",
   "date": "1850",
   "cap": "The **Compromise of 1850** briefly eased sectional conflict, but its harsh **Fugitive Slave Act** let slaveholders seize alleged runaways in the North. The law outraged northerners and energized the Underground Railroad, deepening the moral fury over slavery. Meanwhile in **1854** **Commodore Perry** opened Japanese ports to U.S. trade."
  },
  {
   "img": "images/ch13/strip5.jpg",
   "date": "1854",
   "cap": "Stephen Douglas's **Kansas-Nebraska Act** of **1854** repealed the Missouri Compromise, letting settlers decide slavery by **popular sovereignty**. It destroyed the Whigs and birthed the Republican Party, championing **free labor ideology**, plus the nativist **Know-Nothing Party**."
  },
  {
   "img": "images/ch13/strip6.jpg",
   "date": "1856",
   "cap": "In **1856** violence peaked in **Bleeding Kansas** as proslavery and free-state settlers fought over popular sovereignty. Preston Brooks caned Senator **Charles Sumner** on the Senate floor, shocking the North. Amid the chaos **James Buchanan** won the presidency in an election arrayed by section."
  },
  {
   "img": "images/ch13/strip7.jpg",
   "date": "1857–1858",
   "cap": "The **Dred Scott v. Sandford** decision of **1857** denied Black citizenship and barred Congress from restricting slavery in the territories, undercutting Republicans and popular sovereignty. In the **Lincoln-Douglas debates** of **1858**, Abraham Lincoln rose to fame by branding slavery a moral wrong that must not spread."
  },
  {
   "img": "images/ch13/strip8.jpg",
   "date": "1859–1861",
   "cap": "In **1859** John Brown's raid on Harpers Ferry terrified the South and made him a northern martyr. Lincoln's purely sectional victory in **1860** drove South Carolina and six states to secede and form the Confederacy. In April **1861** the Confederate bombardment of **Fort Sumter** began the Civil War."
  }
 ],
 "14": [
  {
   "img": "images/ch14/strip0.jpg",
   "date": "1861",
   "cap": "The war began when Confederates shelled **Fort Sumter** in **1861**. Confident crowds expected a quick Union win, but green federal troops were routed at the **First Battle of Bull Run** in **1861**, the war's first major clash. The panic exposed how unready both sides were for a long, brutal fight."
  },
  {
   "img": "images/ch14/strip1.jpg",
   "date": "1862",
   "cap": "In **1862**, Ulysses S. Grant seized **Forts Henry and Donelson** and barely held the field at bloody **Shiloh**, while the Union navy captured **New Orleans**. These western victories, contrasting with eastern stalemate under the cautious McClellan, gave the North crucial momentum along the rivers and split the Confederacy's grip on the Mississippi valley."
  },
  {
   "img": "images/ch14/strip2.jpg",
   "date": "1862",
   "cap": "While armies marched, Congress rebuilt the nation in **1862**. The **Homestead Act** gave settlers free western land, the Morrill Act funded state colleges, and new charters launched the **transcontinental railroad**. Paired with greenbacks, national banking, and new taxes, these laws forged a stronger, industrializing Union state during the war."
  },
  {
   "img": "images/ch14/strip3.jpg",
   "date": "1862",
   "cap": "Lee's northern invasion was stopped at the **Battle of Antietam** in September **1862**, the war's bloodiest single day. Emboldened, Lincoln issued the Preliminary **Emancipation Proclamation**. Already enslaved people fleeing to Union lines as **contrabands**, plus pressure from abolitionists and the **Radical Republicans**, had been turning a war for Union into a war against slavery."
  },
  {
   "img": "images/ch14/strip4.jpg",
   "date": "1863",
   "cap": "The **Emancipation Proclamation** took effect on January 1, **1863**, committing the Union to abolition and opening enlistment to some 200,000 Black soldiers and sailors. The famed **54th Massachusetts** proved their valor assaulting Fort Wagner. Their service transformed the army into an agent of freedom and reshaped debates over citizenship and equality."
  },
  {
   "img": "images/ch14/strip5.jpg",
   "date": "1863",
   "cap": "In July **1863**, the twin Union victories at the **Battle of Gettysburg** and the **Battle of Vicksburg** marked the war's turning point, halting Lee and splitting the Confederacy. That same month, resentment over conscription exploded in the deadly **New York City draft riots**. In the South, **King Cotton diplomacy** had already failed to win European recognition."
  },
  {
   "img": "images/ch14/strip6.jpg",
   "date": "1863",
   "cap": "At the dedication of the battlefield cemetery, Lincoln delivered the Gettysburg Address in **1863**, redefining the war as a new birth of freedom. Turning toward peace, he announced his lenient **Ten-Percent Plan** for Reconstruction, offering readmission once one-tenth of a state's voters swore loyalty and accepted emancipation."
  },
  {
   "img": "images/ch14/strip7.jpg",
   "date": "1863–1864",
   "cap": "The war reached far beyond the South. As the Union expanded westward, campaigns devastated Native peoples: the **Navajo** were forced on the brutal Long Walk from **1863**, and the **Sioux** were driven from Minnesota and the Plains. Winona's community survived removal and violence even as the nation fought a war it called one of freedom."
  },
  {
   "img": "images/ch14/strip8.jpg",
   "date": "1864–1866",
   "cap": "Grant's war of attrition in **1864** and Sherman's capture of Atlanta and **March to the Sea** broke the South and secured Lincoln's reelection; Lincoln pocket-vetoed the harsher **Wade-Davis Bill**. Congress passed the **Thirteenth Amendment** in January **1865**; Lee surrendered at Appomattox on April 9, **1865**, and Booth assassinated Lincoln on April 14. In **1866**, Ex parte Milligan barred military trials of civilians where courts function."
  }
 ],
 "15": [
  {
   "img": "images/ch15/strip0.jpg",
   "date": "1865",
   "cap": "In January **1865**, Sherman's **Special Field Order 15** set aside coastal land for freedpeople, sparking the dream of 'forty acres and a mule.' That spring Congress created the **Freedmen's Bureau** to feed refugees, run schools, and enforce northern free-labor ideals. Freedpeople defined freedom broadly: reuniting families, building churches, and above all owning land."
  },
  {
   "img": "images/ch15/strip1.jpg",
   "date": "1865",
   "cap": "President Johnson launched lenient **Presidential Reconstruction** in **1865**, pardoning ex-Confederates who quickly regained power. New southern governments enacted **Black Codes** that restricted freedpeople's rights, forced labor contracts, and tried to recreate slavery in all but name. Johnson soon returned confiscated land to former masters, killing land reform and outraging the Republican North."
  },
  {
   "img": "images/ch15/strip2.jpg",
   "date": "1866",
   "cap": "In **1866** Congress passed the **Civil Rights Act of 1866** over Johnson's veto, declaring African Americans citizens with equal rights. To secure it, Republicans drafted the **Fourteenth Amendment**, guaranteeing birthright citizenship and equal protection. That same year, former Confederates founded the **Ku Klux Klan** in Tennessee, launching a campaign of terror against freedpeople and their allies."
  },
  {
   "img": "images/ch15/strip3.jpg",
   "date": "1867",
   "cap": "The **Reconstruction Act of 1867** placed the South under military rule and granted Black male suffrage, beginning Radical Reconstruction. Northern **carpetbaggers** and Southern white Republican **scalawags** joined freedmen to build interracial governments. New state constitutions created the South's first public school systems and civil rights laws in an unprecedented experiment in democracy."
  },
  {
   "img": "images/ch15/strip4.jpg",
   "date": "1868",
   "cap": "Johnson's obstruction led to the **Impeachment of Andrew Johnson** in **1868**; the Senate acquitted him by a single vote. That year the **Fourteenth Amendment** was ratified into the Constitution, and war hero Ulysses S. Grant won the presidency, signaling voters' support for Congress's Reconstruction program."
  },
  {
   "img": "images/ch15/strip5.jpg",
   "date": "1870-1871",
   "cap": "The **Fifteenth Amendment** of **1870** barred racial discrimination in voting, completing a constitutional revolution—though it excluded women and split the feminist-abolitionist alliance. Hiram Revels became the first Black U.S. senator. In **1870-1871** the **Enforcement Acts** let Grant's prosecutors dismantle the **Ku Klux Klan** and briefly restore order."
  },
  {
   "img": "images/ch15/strip6.jpg",
   "date": "1872-1873",
   "cap": "In **1872** Liberal Republicans bolted the party behind Horace Greeley, who lost badly to Grant, weakening Northern resolve. In **1873** the white-supremacist **Colfax Massacre** killed hundreds of Black Louisianans, the Slaughterhouse Cases narrowed the **Fourteenth Amendment**, and a national depression began, all draining commitment to Reconstruction."
  },
  {
   "img": "images/ch15/strip7.jpg",
   "date": "1875-1876",
   "cap": "Congress passed the **Civil Rights Act of 1875**, but violent 'Mississippi Plan' intimidation in **1875** drove out Reconstruction there as **Redeemers**—conservative white Democrats—retook state after state. In **1876** United States v. Cruikshank (the **Colfax Massacre** case) gutted federal enforcement power, and the Hayes-Tilden presidential election ended in bitter dispute."
  },
  {
   "img": "images/ch15/strip8.jpg",
   "date": "1877",
   "cap": "The disputed **1876** election produced the **Bargain of 1877**: Hayes became president, and the last federal troops left the South, ending Reconstruction. With protection gone, most freedpeople—and many poor white yeomen caught in the **crop-lien system**—sank into **sharecropping** and endless debt, as the era's promise of freedom collapsed."
  }
 ],
 "16": [
  {
   "img": "images/ch16/strip0.jpg",
   "date": "1870s",
   "cap": "After the Civil War a **second industrial revolution** made the U.S. the world's top industrial power. Carnegie used **vertical integration** to control steel from ore to rail, while Rockefeller's **horizontal expansion** let Standard Oil swallow rivals and refine 90% of oil. Admired as captains of industry or feared as **robber barons**, these men defined the **Gilded Age** economy."
  },
  {
   "img": "images/ch16/strip1.jpg",
   "date": "1872–1873",
   "cap": "In **1872** the **Crédit Mobilier** scandal exposed bribery in **Union Pacific** railroad construction, a symbol of the corrupt new era. In **1873** Twain and Warner's novel *The Gilded Age* named the age, glittering on top but rotten beneath, just as a severe depression that year threw the economy into crisis."
  },
  {
   "img": "images/ch16/strip2.jpg",
   "date": "1876",
   "cap": "At the **Battle of the Little Bighorn** in **1876**, Sioux and Cheyenne warriors destroyed Custer's command in the greatest Native victory of the Plains wars. Yet incorporation of the West, railroads, settlers, and the deliberate slaughter of the **buffalo**, doomed the Plains Indians even in triumph, and the army soon crushed the Sioux."
  },
  {
   "img": "images/ch16/strip3.jpg",
   "date": "1877–1879",
   "cap": "The **Great Railroad Strike** of **1877**, the first national labor uprising, was crushed by federal troops. In **1879** Henry George's *Progress and Poverty* proposed a **single tax** on land, and the U.S. returned to the **gold standard**. Out West, **bonanza farms** on the Middle Border and cowboys driving cattle to Kansas railheads foreshadowed agribusiness."
  },
  {
   "img": "images/ch16/strip4.jpg",
   "date": "1883",
   "cap": "The **Civil Service Act of 1883** created merit-based federal hiring, curbing the corrupt spoils system that dominated Gilded Age politics. The same year, the railroads' national reach led them to establish standard **time zones** in **1883**, imposing uniform time on the whole country, a striking sign of how corporate power reshaped everyday American life."
  },
  {
   "img": "images/ch16/strip5.jpg",
   "date": "1886",
   "cap": "In **1886** the **Knights of Labor** peaked and May Day strikes demanded the eight-hour day, but the **Haymarket Affair**, a bombing at a Chicago rally, let employers brand all unions as dangerous radicals. That same year the **Statue of Liberty** was dedicated, offering immigrants a symbol of the freedom the industrial economy so often denied."
  },
  {
   "img": "images/ch16/strip6.jpg",
   "date": "1887–1888",
   "cap": "In **1887** the **Dawes Act** broke up tribal lands into individual plots, costing Native peoples tens of millions of acres, while Congress created the **Interstate Commerce Commission** to regulate railroads, the first federal regulatory agency. In **1888** Edward Bellamy's *Looking Backward* imagined a cooperative future and became a national bestseller."
  },
  {
   "img": "images/ch16/strip7.jpg",
   "date": "1890",
   "cap": "In **1890** the army killed Ghost Dancers in the **Wounded Knee massacre**, ending armed Native resistance. That year the **Sherman Antitrust Act** outlawed monopolies in principle, and Jacob Riis's *How the Other Half Lives* exposed tenement poverty, dramatizing how the richest 1% now held as much income as the bottom half of Americans."
  },
  {
   "img": "images/ch16/strip8.jpg",
   "date": "1895–1905",
   "cap": "In **1895** *United States v. E. C. Knight Co.* gutted the **Sherman Antitrust Act** by exempting manufacturing. Defenders of the unregulated market invoked **Social Darwinism**, survival of the fittest, and the doctrine of **liberty of contract**, which in *Lochner v. New York* (**1905**) voided a maximum-hours law for bakers, leaving the meaning of freedom in an industrial age unresolved."
  }
 ],
 "17": [
  {
   "img": "images/ch17/strip0.jpg",
   "date": "1879",
   "cap": "Fleeing violence and sharecropping debt, tens of thousands of Black southerners joined the **Kansas Exodus** beginning in **1879**, migrating west to seek land and real freedom. These 'Exodusters' hoped the plains offered what Reconstruction's collapse had denied them, though poverty and drought made the promised new start bitterly hard."
  },
  {
   "img": "images/ch17/strip1.jpg",
   "date": "1882",
   "cap": "The **Chinese Exclusion Act** of **1882** barred Chinese immigration, the first federal law to exclude a group by race and nationality. Aimed at the laborers who had built the western railroads, it showed how the nation's boundaries of freedom were narrowing at home even as older promises of open immigration faded."
  },
  {
   "img": "images/ch17/strip2.jpg",
   "date": "1892",
   "cap": "In **1892** the **Homestead Strike** against Carnegie's steel works was crushed by **Pinkerton** agents and state militia, proving unions could not beat giant corporations. That year debt-squeezed farmers turned their Alliance into the **Populist (People's) Party**, whose Omaha platform demanded a graduated income tax, direct election of senators, and public ownership of railroads; **James Weaver** ran for president."
  },
  {
   "img": "images/ch17/strip3.jpg",
   "date": "1893",
   "cap": "In **1893** American sugar planters, backed by U.S. marines, overthrew Hawaii's **Queen Liliuokalani** to push for annexation. That same year a severe economic **depression** struck, collapsing banks and railroads and throwing millions out of work, deepening the labor and farm unrest that Populism had already stirred."
  },
  {
   "img": "images/ch17/strip4.jpg",
   "date": "1894",
   "cap": "In **1894**, jobless protesters in **Coxey's Army** marched on Washington to demand public works, while the **Pullman Strike** paralyzed the nation's railroads. President Cleveland broke it with federal troops and a court injunction, showing how readily national power now crushed labor during the depression."
  },
  {
   "img": "images/ch17/strip5.jpg",
   "date": "1895",
   "cap": "In his **Atlanta Compromise** address of **1895**, **Booker T. Washington** urged Black southerners to accept segregation and pursue economic self-help. Meanwhile Ida B. Wells waged her crusade exposing **lynching**, the terror enforcing white supremacy, and the **American Federation of Labor** organized only skilled white workers, leaving most laborers outside its ranks."
  },
  {
   "img": "images/ch17/strip6.jpg",
   "date": "1896",
   "cap": "In **Plessy v. Ferguson** (**1896**) the Supreme Court upheld 'separate but equal,' blessing segregation, while southern states pursued **disenfranchisement** through poll taxes, literacy tests, and the **grandfather clause**. In that year's realigning election, Democrat **William Jennings Bryan** ran on free silver but lost to lavishly funded Republican William McKinley, forging a majority lasting until 1932."
  },
  {
   "img": "images/ch17/strip7.jpg",
   "date": "1898",
   "cap": "The sinking of the **U.S.S. Maine** in **1898** helped launch the **Spanish-American War**, sparked by Cuba's revolt. Swift victories at Manila Bay and Santiago brought Puerto Rico, Guam, and the Philippines under U.S. rule, and Hawaii was annexed that year, making the United States an overseas empire almost overnight."
  },
  {
   "img": "images/ch17/strip8.jpg",
   "date": "1899–1900",
   "cap": "In **1899** the bloody **Philippine War** began against Emilio Aguinaldo's independence movement, and John Hay announced the Open Door Policy for trade with China. In **1900** the Gold Standard Act made gold the sole currency basis, and McKinley again defeated Bryan in an election Americans framed as 'republic or empire.'"
  },
  {
   "img": "images/ch17/strip9.jpg",
   "date": "1901–1904",
   "cap": "The **Platt Amendment** of **1901** bound Cuba as a U.S. protectorate, granting Washington the right to intervene and keep naval bases. Beginning that year, the **Insular Cases** (**1901–1904**) ruled that the Constitution did not fully follow the flag to new territories, leaving Americans to debate whether their republic had become an empire."
  }
 ],
 "18": [
  {
   "img": "images/ch18/strip0.jpg",
   "date": "1889",
   "cap": "In **1889**, **Jane Addams** founded **Hull House** in Chicago, launching the American settlement-house movement. These houses served crowded immigrant neighborhoods and pushed cities and states toward protective legislation, becoming a seedbed of the broader **Progressive** reform crusade to humanize industrial capitalism."
  },
  {
   "img": "images/ch18/strip1.jpg",
   "date": "1901",
   "cap": "In **1901**, an anarchist assassinated McKinley, and **Theodore Roosevelt** became president, promising ordinary Americans a **Square Deal**. That same year the **Socialist Party** was founded; under Eugene Debs it demanded 'industrial democracy' and would peak in **1912** as a serious voice for working people."
  },
  {
   "img": "images/ch18/strip2.jpg",
   "date": "1904",
   "cap": "In **1904**, the Supreme Court ordered the Northern Securities railroad holding company dissolved, a landmark antitrust victory for the **Square Deal**. The ruling showed the federal government would police giant corporations, cementing 'trust-busting' as a signature of the new activist national state."
  },
  {
   "img": "images/ch18/strip3.jpg",
   "date": "1905",
   "cap": "In **1905**, the radical **Industrial Workers of the World (IWW)** organized in Chicago, uniting the unskilled immigrants the AFL ignored. They rebelled against **scientific management**, which used stopwatches to control labor, and against **Fordism** — Henry Ford's assembly line and five-dollar day built on mass production and mass consumption."
  },
  {
   "img": "images/ch18/strip4.jpg",
   "date": "1906",
   "cap": "In **1906**, **muckrakers** like Upton Sinclair exposed industry's horrors; his novel The Jungle spurred the Meat Inspection and Pure Food and Drug Acts. The same year the Hepburn Act strengthened railroad regulation, advancing Roosevelt's consumer protection and his sweeping **conservation movement** to safeguard forests, water, and public land."
  },
  {
   "img": "images/ch18/strip5.jpg",
   "date": "1908",
   "cap": "In **1908**, **Muller v. Oregon** upheld maximum-hours legislation for women workers, accepting sociological evidence about labor conditions. The decision expanded protective legislation championed by settlement reformers, though its reasoning about women's 'special' needs also revealed limits within Progressive thought."
  },
  {
   "img": "images/ch18/strip6.jpg",
   "date": "1911",
   "cap": "In **1911**, the **Triangle Shirtwaist fire** killed about 146 workers trapped behind locked doors, dramatizing the human cost of industrial growth. Public outrage ignited factory-reform legislation and strengthened demands for government action, giving urgent momentum to the whole Progressive movement."
  },
  {
   "img": "images/ch18/strip7.jpg",
   "date": "1912",
   "cap": "The four-way election of **1912** pitted Wilson's **New Freedom** against Roosevelt's **New Nationalism**, Taft, and Debs; Wilson won. Feminists like Margaret Sanger tied freedom to the **birth-control movement**, while Robert La Follette's **Wisconsin Idea** made his state a 'laboratory of democracy' guided by experts."
  },
  {
   "img": "images/ch18/strip8.jpg",
   "date": "1913–1916",
   "cap": "In **1913**, the Sixteenth and **Seventeenth Amendment** were ratified — the latter for direct election of senators — and the **Federal Reserve** was created. In **1914** the Clayton Act shielded unions and the **FTC** was established; the Keating-Owen child-labor and Adamson eight-hour laws of **1916** capped Wilson's activist first term."
  }
 ],
 "19": [
  {
   "img": "images/ch19/strip0.jpg",
   "date": "1903-1904",
   "cap": "Pursuing **liberal internationalism**, Roosevelt backed Panama's **1903** break from Colombia to seize the **Panama Canal** Zone. In **1904** the **Roosevelt Corollary** declared a U.S. 'international police power' over the Western Hemisphere, threatening intervention to keep order and protect American trade."
  },
  {
   "img": "images/ch19/strip1.jpg",
   "date": "1909",
   "cap": "After the Springfield, Illinois, lynching, reformers founded the **NAACP** in **1909** to fight for Black civil rights through the courts and press. Its leaders, including W.E.B. Du Bois, would give voice to a rising militancy against segregation, disfranchisement, and mob violence."
  },
  {
   "img": "images/ch19/strip2.jpg",
   "date": "1914-1915",
   "cap": "In **1914** World War I broke out in Europe just as the **Panama Canal** opened. Wilson proclaimed neutrality, but in **1915** a German U-boat sank the **Lusitania**, killing 124 Americans and inflaming U.S. opinion against Germany's submarine warfare."
  },
  {
   "img": "images/ch19/strip3.jpg",
   "date": "1917",
   "cap": "The **Zimmermann Telegram** of **1917**, urging Mexico to attack the U.S., pushed America into war that April to make the world 'safe for democracy.' The **Selective Service Act** drafted millions of soldiers. That same year the Russian Revolution began, unsettling the world."
  },
  {
   "img": "images/ch19/strip4.jpg",
   "date": "1917-1918",
   "cap": "The **War Industries Board** mobilized the economy while the **Committee on Public Information** flooded the nation with propaganda and Liberty bonds. The **Espionage and Sedition Acts** of **1917-1918** criminalized dissent, jailing socialist Eugene Debs and unleashing coercive '100 percent Americanism.'"
  },
  {
   "img": "images/ch19/strip5.jpg",
   "date": "1916-1919",
   "cap": "In the **Great Migration**, half a million Black southerners moved north for jobs and freedom, meeting deadly riots in East St. Louis and elsewhere. **Marcus Garvey** preached Black nationalism and pride, while the **NAACP** and Du Bois pressed for justice amid rising racial militancy."
  },
  {
   "img": "images/ch19/strip6.jpg",
   "date": "1918",
   "cap": "In **1918** Wilson announced his **Fourteen Points**, promising self-determination, free trade, open diplomacy, and a **League of Nations**. American troops helped turn the tide at the **Meuse-Argonne** offensive, and in November an armistice finally ended the fighting."
  },
  {
   "img": "images/ch19/strip7.jpg",
   "date": "1919",
   "cap": "The **Treaty of Versailles** was signed in **1919**, but it betrayed colonial hopes for self-determination. At home a great steel strike, brutal race riots, and the **Red Scare** convulsed the nation as officials hunted suspected radicals. The **Eighteenth Amendment**, ratified that year, launched Prohibition."
  },
  {
   "img": "images/ch19/strip8.jpg",
   "date": "1920-1921",
   "cap": "In **1920** the **Nineteenth Amendment**, won by Alice Paul's militant campaigning, gave women the vote; the Senate rejected the **Treaty of Versailles** and **League of Nations**, and Harding won on a 'return to normalcy.' The **Red Scare** faded, but in **1921** the Tulsa riot destroyed a thriving Black community."
  }
 ],
 "20": [
  {
   "img": "images/ch20/strip0.jpg",
   "date": "1919-1920",
   "cap": "In **Schenck v. United States** (**1919**) the Court upheld silencing wartime dissent, but soon **Holmes and Brandeis** began defending free speech. In **1920** national **Prohibition** took effect and the **American Civil Liberties Union** was founded, launching a modern civil-liberties movement."
  },
  {
   "img": "images/ch20/strip1.jpg",
   "date": "1920-1921",
   "cap": "In **1920** Italian anarchists Sacco and Vanzetti were arrested; their **1921** trial in the **Sacco-Vanzetti case** exposed deep nativist prejudice. That same year an emergency quota act temporarily restricted European immigration, foreshadowing far harsher limits to come."
  },
  {
   "img": "images/ch20/strip2.jpg",
   "date": "1923",
   "cap": "In **1923** Harding died and Coolidge became president as the **Teapot Dome** oil-bribery scandal exposed corruption. The conservative Court struck a minimum-wage law in **Adkins v. Children's Hospital (1923)**, while **Meyer v. Nebraska** protected cultural pluralism, giving civil liberties constitutional footing."
  },
  {
   "img": "images/ch20/strip3.jpg",
   "date": "1924",
   "cap": "The **Immigration Act of 1924** imposed national-origins quotas, slashed southern and eastern European immigration, barred Asians entirely, and invented the 'illegal alien.' Coolidge won in a landslide over Davis and La Follette, while the millions-strong **Second Ku Klux Klan** menaced immigrants, Catholics, and Jews."
  },
  {
   "img": "images/ch20/strip4.jpg",
   "date": "1925",
   "cap": "The **Scopes trial (1925)** in Dayton, Tennessee, dramatized **Fundamentalism** clashing with modern secular culture. Meanwhile **Flappers** symbolized women's new personal freedom, even as the **Equal Rights Amendment** split feminists over whether equality should erase protective labor laws for women."
  },
  {
   "img": "images/ch20/strip5.jpg",
   "date": "1925-1927",
   "cap": "The Great Migration fed the **Harlem Renaissance**, whose writers proclaimed a defiant 'New Negro.' In **1927** Lindbergh flew solo across the Atlantic to national adulation, but that same year Sacco and Vanzetti were executed, closing a case that had stirred worldwide protest."
  },
  {
   "img": "images/ch20/strip6.jpg",
   "date": "1928",
   "cap": "The 1920s boom in autos, radios, and appliances fed a consumer culture of installment buying and celebrity heroes. In **1928** Hoover defeated Al Smith, the first Catholic major-party nominee, a landslide that seemed to ratify Republican business prosperity built on tax cuts and high tariffs."
  },
  {
   "img": "images/ch20/strip7.jpg",
   "date": "1929-1930",
   "cap": "In October **1929** the **Stock market crash** on Black Tuesday opened the Great Depression, exposing unequal incomes, farm distress, and reckless speculation. In **1930** the **Smoot-Hawley Tariff (1930)** raised duties to record levels, choking world trade and deepening the global slump."
  },
  {
   "img": "images/ch20/strip8.jpg",
   "date": "1931-1932",
   "cap": "Unions had lost over 2 million members under the open-shop **American Plan / welfare capitalism**, and by **1932** output had fallen a third with unemployment at 25 percent. Hoover's belated **Reconstruction Finance Corporation (1932)** lent to banks but failed to stem the Depression; Bonus marchers were driven from Washington."
  }
 ],
 "21": [
  {
   "img": "images/ch21/strip0.jpg",
   "date": "1931",
   "cap": "In **1931**, nine Black teenagers were arrested and falsely accused in the **Scottsboro case**, which became an international civil rights cause as the **Great Depression** deepened. Their trials exposed the racism of the Jim Crow South and drew activists from around the world to their defense."
  },
  {
   "img": "images/ch21/strip1.jpg",
   "date": "1932",
   "cap": "In **1932**, **Franklin D. Roosevelt** crushed **Herbert Hoover** in a landslide amid the worst of the Depression, promising a **New Deal** for the American people. His confident, experimental spirit contrasted with Hoover's exhausted caution and gave desperate voters fresh hope."
  },
  {
   "img": "images/ch21/strip2.jpg",
   "date": "1933",
   "cap": "FDR's first **Hundred Days** in **1933** unleashed unmatched legislation: the **Emergency Banking Act** rescued banks, the **National Recovery Administration (NRA)** set industry codes, the **Agricultural Adjustment Act (AAA)** paid farmers to cut output, the **Civilian Conservation Corps (CCC)** hired the jobless, and the **Tennessee Valley Authority (TVA)** brought cheap power south. The **Twenty-first Amendment** ended Prohibition."
  },
  {
   "img": "images/ch21/strip3.jpg",
   "date": "1934",
   "cap": "In **1934**, Senator Huey Long launched the **Share Our Wealth movement**, demanding bold redistribution as roughly 2,000 strikes swept the nation. On the Great Plains, drought and ruined soil intensified the **Dust Bowl**, driving desperate families off their land and pushing FDR to go further than the First New Deal had gone."
  },
  {
   "img": "images/ch21/strip4.jpg",
   "date": "1935",
   "cap": "The **Second New Deal** of **1935** shifted from recovery to security: the **Works Progress Administration (WPA)** employed millions, the **Wagner Act** guaranteed the right to unionize, and the **Social Security Act** created old-age pensions and unemployment insurance. That year the Supreme Court voided the **NRA**, and industrial unionists founded the **Congress of Industrial Organizations (CIO)**."
  },
  {
   "img": "images/ch21/strip5.jpg",
   "date": "1934–1936",
   "cap": "The **Indian New Deal**, launched by the **Indian Reorganization Act** in **1934**, reversed decades of forced assimilation, restored tribal self-government, and ended the breakup of reservation land. Championed by John Collier, it let people like Winona revive their cultures, though it did not end deep reservation poverty."
  },
  {
   "img": "images/ch21/strip6.jpg",
   "date": "1936",
   "cap": "In **1936**, the Supreme Court struck down the **AAA**, but FDR won reelection with over 60 percent of the vote, cementing a durable New Deal coalition. That same year British economist John Maynard Keynes published his **General Theory**, whose argument for deficit spending would soon shape the administration's thinking."
  },
  {
   "img": "images/ch21/strip7.jpg",
   "date": "1937",
   "cap": "In **1937**, the **Flint sit-down strike** won UAW recognition from General Motors, proving the power of the **sit-down strike** and the **CIO**. FDR's **court packing plan** failed, yet the Court began upholding New Deal laws. Then a sharp recession struck, pushing the administration toward Keynesian deficit spending."
  },
  {
   "img": "images/ch21/strip8.jpg",
   "date": "1938–1940",
   "cap": "The **Fair Labor Standards Act** of **1938** set a national minimum wage and banned child labor, while **HUAC** was established. In **1939**, Eleanor Roosevelt arranged Marian Anderson's Lincoln Memorial concert after the DAR barred her. By **1940**, a conservative coalition stalled reform; unemployment still topped 15 percent as war loomed. **FHA** redlining, meanwhile, had deepened housing segregation throughout."
  }
 ],
 "22": [
  {
   "img": "images/ch22/strip0.jpg",
   "date": "1937–1938",
   "cap": "In **1937** Japan launched a full-scale war on China, including the massacre of civilians at Nanjing. In **1938** Britain and France appeased Hitler at Munich after Germany annexed Austria and the Sudetenland. Scarred by World War I, most Americans wanted no part of it, and Congress had passed the **Neutrality Acts** barring arms sales to warring nations."
  },
  {
   "img": "images/ch22/strip1.jpg",
   "date": "1939–1940",
   "cap": "In **1939** Germany invaded Poland after the Nazi-Soviet pact, and Britain and France declared war. In **1940** France fell to the German blitzkrieg; **FDR** won an unprecedented third term and the first peacetime draft began. Roosevelt edged toward the Allies with 'cash and carry' sales and an oil embargo against Japan."
  },
  {
   "img": "images/ch22/strip2.jpg",
   "date": "1941",
   "cap": "In **1941** FDR's **Four Freedoms** speech—of speech and worship, from want and fear—framed the struggle, and Congress passed the **Lend-Lease Act** to arm the Allies. Then Japan's surprise attack on **Pearl Harbor** on **December 7, 1941** brought the United States fully into the war."
  },
  {
   "img": "images/ch22/strip3.jpg",
   "date": "1942",
   "cap": "In **1942** Executive Order 9066 sent over 110,000 people to **Japanese-American internment** camps, most of them citizens. The U.S. Navy's victory at the **Battle of Midway** turned the Pacific war, and **CORE** was founded, pioneering nonviolent protest against segregation."
  },
  {
   "img": "images/ch22/strip4.jpg",
   "date": "1941–1945",
   "cap": "War mobilization doubled the GNP and ended unemployment; millions of women took industrial jobs symbolized by Rosie the Riveter. A. Philip Randolph's march threat won **Executive Order 8802** and the **FEPC**, banning defense discrimination. Some 700,000 Black southerners joined the **Second Great Migration**, and the **Double-V campaign**—victory abroad and at home—launched the modern civil rights movement."
  },
  {
   "img": "images/ch22/strip5.jpg",
   "date": "1943",
   "cap": "In **1943** race violence erupted in the Detroit riot and the Los Angeles **zoot suit riots**, targeting Mexican-American youths. The **Bracero program** brought Mexican laborers to fill wartime shortages, and Congress repealed Chinese exclusion, easing decades of discrimination."
  },
  {
   "img": "images/ch22/strip6.jpg",
   "date": "1944",
   "cap": "In **1944** Allied forces landed at Normandy on **D-Day** in June, opening the drive to liberate western Europe. Congress passed the **GI Bill of Rights**, funding college and homes for veterans; the **Bretton Woods conference** built the postwar economic order; and the Court upheld internment in **Korematsu v. United States**."
  },
  {
   "img": "images/ch22/strip7.jpg",
   "date": "1945",
   "cap": "In early **1945** the Big Three met at **Yalta** to shape the postwar world. Soviet victory at Stalingrad had already broken Germany in the east, and advancing Allies uncovered the full horror of the **Holocaust**, the Nazi murder of six million Jews. FDR died in April, and Harry Truman became president."
  },
  {
   "img": "images/ch22/strip8.jpg",
   "date": "1945",
   "cap": "Germany surrendered on V-E Day in May **1945**. In August, atomic bombs destroyed **Hiroshima and Nagasaki** and Japan surrendered. The **United Nations** Charter took effect, leaving the United States the world's dominant power—though rising tension with the Soviet Union already signaled a coming Cold War."
  }
 ],
 "23": [
  {
   "img": "images/ch23/strip0.jpg",
   "date": "1946",
   "cap": "In **1946** George Kennan's **Long Telegram** warned that Soviet expansion must be checked, launching the policy of **Containment** at the dawn of the **Cold War**. Churchill declared an **Iron curtain** had split Europe, while a giant postwar strike wave paralyzed American industry."
  },
  {
   "img": "images/ch23/strip1.jpg",
   "date": "1947",
   "cap": "The **1947** **Truman Doctrine** pledged aid to Greece and Turkey as a global defense of 'free peoples,' and the **Marshall Plan** poured billions into rebuilding western Europe. Congress passed the anti-union **Taft-Hartley Act** over Truman's veto, HUAC opened its Hollywood probe, and Jackie Robinson integrated baseball."
  },
  {
   "img": "images/ch23/strip2.jpg",
   "date": "1947",
   "cap": "In **1947** HUAC's Hollywood hearings jailed the **Hollywood Ten** for refusing to answer questions about communism, and the studios blacklisted them. This purge helped ignite the fearful crusade later named **McCarthyism**, which would cost thousands of dissenters their jobs across American life."
  },
  {
   "img": "images/ch23/strip3.jpg",
   "date": "1948",
   "cap": "In **1948** Truman desegregated the armed forces and backed a strong civil rights plank, driving Strom Thurmond's **Dixiecrats** out of the Democratic convention. That year the UN adopted the **Universal Declaration of Human Rights**, and Truman's civil rights push reflected his broader liberal aims."
  },
  {
   "img": "images/ch23/strip4.jpg",
   "date": "1948",
   "cap": "When the Soviets imposed the **Berlin blockade and airlift** in **1948**, Allied planes supplied the city for eleven months. At home Truman's **Fair Deal**—health insurance, higher wages, expanded Social Security—was largely blocked by a conservative coalition, yet Truman stunned pollsters by defeating Dewey."
  },
  {
   "img": "images/ch23/strip5.jpg",
   "date": "1949",
   "cap": "In **1949** the United States joined **NATO**, its first permanent European alliance. That same year the Soviet Union tested an atomic bomb and Mao's communists won the Chinese civil war—twin shocks that spurred **NSC-68**'s call for a massive American military buildup."
  },
  {
   "img": "images/ch23/strip6.jpg",
   "date": "1950",
   "cap": "In **1950** Senator Joseph McCarthy claimed communists riddled the State Department, giving **McCarthyism** its name. **NSC-68** urged a huge arms buildup, and North Korea's invasion of the South began the **Korean War**, in which U.S.-led UN forces fought a brutal three-year conflict."
  },
  {
   "img": "images/ch23/strip7.jpg",
   "date": "1951",
   "cap": "In **1951**, during the **Korean War**, Truman fired General MacArthur for insubordination, defending civilian control. That same year Julius and Ethel Rosenberg were convicted of conspiring to commit atomic espionage—a case that deepened the fear driving **McCarthyism** across the country."
  },
  {
   "img": "images/ch23/strip8.jpg",
   "date": "1952–1954",
   "cap": "In **1952** the McCarran-Walter Act kept national-origin quotas and allowed deporting immigrant communists over Truman's veto. In **1953** an armistice halted the **Korean War** near the thirty-eighth parallel and the Rosenbergs were executed. The televised **1954** Army-McCarthy hearings exposed **McCarthyism**, and the Senate condemned McCarthy."
  }
 ],
 "24": [
  {
   "img": "images/ch24/strip0.jpg",
   "date": "1947",
   "cap": "In **1947** builders broke ground on the first **Levittown**, the model for mass-produced postwar suburbia sold on cheap FHA and VA mortgages. These affordable tract homes filled with families riding the **baby boom**, as returning veterans married and prosperity made large families possible for millions of new homeowners."
  },
  {
   "img": "images/ch24/strip1.jpg",
   "date": "1952",
   "cap": "In **1952** Dwight Eisenhower defeated Democrat Adlai Stevenson, launching an era of 'Modern Republicanism' that accepted the New Deal while courting business. That same year the United States tested the first hydrogen bomb, pushing the Cold War into a terrifying nuclear age of ever-larger weapons."
  },
  {
   "img": "images/ch24/strip2.jpg",
   "date": "1953",
   "cap": "In **1953** a CIA-backed coup ousted Iran's elected Mossadegh, an early sign the Cold War was shifting to the Third World. The same year Stalin died and the Korean armistice was signed, opening a chance for Eisenhower's cautious diplomacy amid his doctrine of **massive retaliation**."
  },
  {
   "img": "images/ch24/strip3.jpg",
   "date": "1954",
   "cap": "In **1954** Thurgood Marshall won **Brown v. Board of Education**, in which the Warren Court ruled segregated schools inherently unequal. Abroad the CIA toppled Guatemala's elected Arbenz, and the **Geneva Accords** divided Vietnam, after which American aid would prop up Diem's regime in the South."
  },
  {
   "img": "images/ch24/strip4.jpg",
   "date": "1955",
   "cap": "In **1955** Rosa Parks's arrest sparked the **Montgomery bus boycott**, a year-long protest that thrust the young Reverend **Martin Luther King Jr.** into national leadership of church-based nonviolent resistance. In the same year the AFL and CIO merged, capping the labor-management social contract that traded union restraint for rising postwar wages."
  },
  {
   "img": "images/ch24/strip5.jpg",
   "date": "1956",
   "cap": "In **1956** Southern congressmen issued the **Southern Manifesto**, pledging 'massive resistance' to school integration. That year Congress funded the **interstate highway system**, knitting the car-centered suburbs into daily life, and the **Montgomery bus boycott** triumphed when the Supreme Court voided bus segregation."
  },
  {
   "img": "images/ch24/strip6.jpg",
   "date": "1957",
   "cap": "In **1957** Eisenhower reluctantly sent federal troops to the **Little Rock crisis** to integrate Central High. King and allied ministers founded the **Southern Christian Leadership Conference (SCLC)** to coordinate the movement. Meanwhile the Soviets launched **Sputnik**, shocking Americans and igniting fears they had fallen behind in the arms race."
  },
  {
   "img": "images/ch24/strip7.jpg",
   "date": "1958–1959",
   "cap": "In **1958** the National Defense Education Act, spurred by Sputnik, gave the first major federal funding to higher education. In **1959** Nixon and Khrushchev clashed in the **kitchen debate** in Moscow, equating American freedom with consumer abundance. Yet dissenters like **the Beats** mocked the era's suburban conformity and materialism."
  },
  {
   "img": "images/ch24/strip8.jpg",
   "date": "1960–1961",
   "cap": "In **1960** the U-2 incident wrecked a planned summit, and John F. Kennedy narrowly beat Nixon after the first televised presidential debates. In **1961** Eisenhower's Farewell Address warned against the **military-industrial complex**. Beneath the boom, **urban renewal** and racist mortgage policy confined Black Americans and Latinos to declining cities as white families fled to the suburbs."
  }
 ],
 "25": [
  {
   "img": "images/ch25/strip0.jpg",
   "date": "1960",
   "cap": "In February **1960**, four Black students launched **Sit-ins** at a Greensboro lunch counter, sparking a wave of student protest across the South. Under Ella Baker's guidance, young activists founded **SNCC** to coordinate the movement, opening a decade of nonviolent direct action against segregation."
  },
  {
   "img": "images/ch25/strip1.jpg",
   "date": "1961",
   "cap": "In **1961**, CORE's **Freedom Rides** sent integrated buses south to test desegregation orders on interstate travel, meeting mobs and firebombs. Abroad, Kennedy's **Bay of Pigs** invasion of Cuba failed humiliatingly, and the Soviets sealed off their sector by building the **Berlin Wall**, hardening the Cold War divide."
  },
  {
   "img": "images/ch25/strip2.jpg",
   "date": "1962",
   "cap": "In **1962**, the **Cuban missile crisis** brought the world to the brink of nuclear war until Kennedy forced Soviet withdrawal. That same year SDS issued the **Port Huron Statement**, demanding 'participatory democracy,' and Rachel Carson's Silent Spring warned of pesticides, seeding modern environmentalism."
  },
  {
   "img": "images/ch25/strip3.jpg",
   "date": "1963",
   "cap": "In **1963**, King's Birmingham campaign and his 'Letter from Birmingham Jail' met dogs and fire hoses, shocking the world and pushing Kennedy to back a civil rights bill. The **March on Washington** climaxed the nonviolent phase with King's 'I Have a Dream.' In November, Kennedy was assassinated in Dallas."
  },
  {
   "img": "images/ch25/strip4.jpg",
   "date": "1964",
   "cap": "In **1964**, Johnson signed the **Civil Rights Act of 1964**, banning discrimination in jobs and public accommodations. The **Freedom Summer** drive registered Black voters in Mississippi despite deadly violence. After a murky clash at sea, Congress passed the **Gulf of Tonkin resolution**, handing Johnson a blank check for war in Vietnam."
  },
  {
   "img": "images/ch25/strip5.jpg",
   "date": "1965",
   "cap": "After Selma's marches, the **Voting Rights Act of 1965** secured federal protection of Black voting. Frustration exploded in the Watts uprising, and **Malcolm X** was assassinated as his separatist message spread. The **Hart-Celler Act** scrapped racist immigration quotas, reopening America to the world."
  },
  {
   "img": "images/ch25/strip6.jpg",
   "date": "1965–1966",
   "cap": "Johnson's **Great Society** and **War on Poverty** created Medicare, Medicaid, Head Start, and food stamps to fight need. In 1966 the National Organization for Women launched second-wave feminism, echoing Betty Friedan's **The Feminine Mystique**. That year Stokely Carmichael's cry for **Black Power** rose and the Black Panther Party formed, as legal wins left economic inequality untouched."
  },
  {
   "img": "images/ch25/strip7.jpg",
   "date": "1967",
   "cap": "In **1967**, urban uprisings tore through Newark and Detroit, exposing the limits of legal gains in the North. As Johnson escalated Vietnam past half a million troops, roughly 100,000 protesters marched on the Pentagon, swelling a mass antiwar movement led by students of the New Left."
  },
  {
   "img": "images/ch25/strip8.jpg",
   "date": "1968–1969",
   "cap": "In **1968**, the **Tet offensive** shattered faith in the war; Johnson declined to run, King and Robert Kennedy were assassinated, and Chicago's convention descended into chaos before Nixon's law-and-order victory. Inspired by civil rights, new movements surged—Chavez's farm workers and Native American activism—as Winona joined the Red Power cause. In **1969** the **Stonewall uprising** launched gay liberation and Woodstock celebrated the counterculture."
  },
  {
   "img": "images/ch25/strip9.jpg",
   "date": "1973",
   "cap": "The Warren Court expanded rights across the decade, from **Miranda** warnings to a right of privacy. Building on those privacy rulings, **Roe v. Wade** in **1973** established a constitutional right to abortion. Even as Nixon's win showed liberalism in retreat, America emerged a freer, more open society."
  }
 ],
 "26": [
  {
   "img": "images/ch26/strip0.jpg",
   "date": "1970",
   "cap": "In **1970** Nixon widened the war by ordering the invasion of **Cambodia**, igniting furious campus protest. At **Kent State**, National Guardsmen opened fire and killed four students, shocking the nation. Anger over Vietnam deepened as reports spread of the earlier **My Lai massacre**, where U.S. soldiers had slaughtered hundreds of unarmed Vietnamese civilians."
  },
  {
   "img": "images/ch26/strip1.jpg",
   "date": "1971",
   "cap": "In **1971** the **Pentagon Papers** were published, exposing decades of official deception about the Vietnam War and eroding public trust in government. That same year Nixon took the United States off the **gold standard**, ending the postwar system of fixed exchange rates and setting the stage for the economic turbulence to come."
  },
  {
   "img": "images/ch26/strip2.jpg",
   "date": "1972",
   "cap": "In **1972** Nixon and Kissinger practiced realist diplomacy: Nixon visited China and signed the **SALT** arms-control treaty in Moscow, launching an era of **détente**. Congress passed **Title IX** and sent the **ERA** to the states. But that June, burglars broke into Democratic headquarters, beginning the **Watergate** scandal."
  },
  {
   "img": "images/ch26/strip3.jpg",
   "date": "1973",
   "cap": "In **1973** the **Paris Peace Accords** ended U.S. combat in Vietnam. Then the Arab **oil embargo** quadrupled energy prices, fueling **stagflation**—stagnant growth paired with high inflation that defied liberal remedies. Congress passed the **War Powers Act** to curb the president's ability to wage war without its approval."
  },
  {
   "img": "images/ch26/strip4.jpg",
   "date": "1974–1975",
   "cap": "Facing impeachment over **Watergate**, Nixon became the first president to resign in **1974**; **Gerald Ford** succeeded him and pardoned him. In **1975** South Vietnam fell to the North, ending the war in defeat. Ford's thin record included the **Helsinki Accords**, which linked European security to human-rights pledges."
  },
  {
   "img": "images/ch26/strip5.jpg",
   "date": "1976",
   "cap": "In **1976** **Jimmy Carter**, campaigning as a post-Watergate outsider, narrowly defeated Ford. He inherited an economy reshaped by **deindustrialization**, as manufacturing jobs fled the Rust Belt for the low-wage **Sunbelt** and overseas. Real wages began a long decline and labor unions steadily weakened across the industrial North."
  },
  {
   "img": "images/ch26/strip6.jpg",
   "date": "1978",
   "cap": "In **1978** California's **Proposition 13** slashed property taxes, sparking a nationwide anti-tax rebellion. The Supreme Court's **Regents v. Bakke** decision barred rigid racial quotas while allowing race as one admissions factor. That year Carter also brokered the **Camp David Accords**, a historic peace between Egypt and Israel."
  },
  {
   "img": "images/ch26/strip7.jpg",
   "date": "1979",
   "cap": "In **1979** the **Three Mile Island** accident frightened the nation, a second oil shock hit, and Iranian revolutionaries seized American hostages, making Carter appear helpless when the Soviets also invaded Afghanistan. That year the **Moral Majority** was founded, mobilizing the evangelical Religious Right and swelling a rising conservative movement."
  },
  {
   "img": "images/ch26/strip8.jpg",
   "date": "1980–1987",
   "cap": "In **1980** **Ronald Reagan** defeated Carter, launching the **Reagan Revolution**. In **1981** his supply-side **Reaganomics** won huge tax cuts, and he fired 13,000 striking air traffic controllers. The **Iran-Contra affair** hearings in **1987** exposed illegal arms deals, yet that year Reagan and **Gorbachev** agreed to eliminate intermediate-range nuclear missiles, thawing the Cold War."
  }
 ],
 "27": [
  {
   "img": "images/ch27/strip0.jpg",
   "date": "1989",
   "cap": "In **1989** the **Berlin Wall** fell as communist regimes collapsed peacefully across eastern Europe, while Chinese troops crushed pro-democracy protesters in **Tiananmen Square**. The Cold War was ending, leaving the U.S. the lone superpower. President **George H. W. Bush** proclaimed a **new world order**."
  },
  {
   "img": "images/ch27/strip1.jpg",
   "date": "1990–1991",
   "cap": "In **1991** Bush led an international coalition in the **Gulf War**, expelling Iraq from Kuwait. That year the **Soviet Union** dissolved into fifteen nations, ending the Cold War. At home the **Americans with Disabilities Act** (**1990**) barred discrimination and required accessibility for millions of citizens."
  },
  {
   "img": "images/ch27/strip2.jpg",
   "date": "1992",
   "cap": "In **1992** the acquittal of officers who beat Rodney King sparked the **Rodney King riots**, exposing persistent racial injustice. That fall **Bill Clinton** won a three-way race, blending social liberalism with promises to shrink government, while **Ross Perot** took nearly a fifth of the vote."
  },
  {
   "img": "images/ch27/strip3.jpg",
   "date": "1993",
   "cap": "In **1993** Clinton pushed **NAFTA** through Congress, creating a North American free-trade zone that erased tariffs among the U.S., Canada, and Mexico. He also expanded the Earned Income Tax Credit, but his ambitious health-care plan soon collapsed in Congress."
  },
  {
   "img": "images/ch27/strip4.jpg",
   "date": "1994",
   "cap": "In **1994** Newt Gingrich's **Contract with America** carried Republicans to sweeping control of Congress. That same year the **Rwandan genocide** killed more than 800,000 people while Clinton stood by, an act of **ethnic cleansing** the U.S. failed to stop."
  },
  {
   "img": "images/ch27/strip5.jpg",
   "date": "1995",
   "cap": "On April 19, **1995**, antigovernment extremist Timothy McVeigh set off a truck bomb in the **Oklahoma City bombing**, destroying the Murrah federal building and killing 168 people. The attack marked the deadliest act of domestic terrorism in American history to that point."
  },
  {
   "img": "images/ch27/strip6.jpg",
   "date": "1996",
   "cap": "Declaring 'the era of big government is over,' Clinton signed the **1996** law abolishing AFDC welfare and won reelection over Bob Dole. Post-1965 immigration remade society, making Latinos the largest minority and igniting **Culture Wars** over **multiculturalism**, bilingualism, and family values."
  },
  {
   "img": "images/ch27/strip7.jpg",
   "date": "1998–1999",
   "cap": "The House impeached Clinton over the Lewinsky scandal in **1998**; the Senate acquitted him in the **Clinton impeachment**'s conclusion in early **1999**. That year NATO waged war over Kosovo against **ethnic cleansing**, Congress repealed Glass-Steagall, and the **Battle of Seattle** protesters disrupted the WTO, challenging **globalization**."
  },
  {
   "img": "images/ch27/strip8.jpg",
   "date": "2000–2001",
   "cap": "In **2000** the Supreme Court's **Bush v. Gore** ruling halted Florida's recount, handing **George W. Bush** the presidency despite his loss of the popular vote. On **September 11, 2001**, **Al Qaeda** hijackers struck the World Trade Center and Pentagon, killing about 3,000 and shattering America's post–Cold War security."
  }
 ],
 "28": [
  {
   "img": "images/ch28/strip0.jpg",
   "date": "2001",
   "cap": "On September 11, **2001**, attacks killed about 3,000 people and remade the Bush presidency. Under the **Bush Doctrine** ('either you are with us, or with the terrorists'), the U.S. launched the **War in Afghanistan** and toppled the Taliban, while Congress passed the **USA Patriot Act**, hugely expanding surveillance."
  },
  {
   "img": "images/ch28/strip1.jpg",
   "date": "2002",
   "cap": "In **2002**, Bush branded Iraq, Iran, and North Korea an 'axis of evil,' signaling wider confrontation. That same year the **Guantánamo Bay** detention camp opened, holding detainees indefinitely without trial; harsh interrogations amounting to torture would later stain America's global reputation."
  },
  {
   "img": "images/ch28/strip2.jpg",
   "date": "2003",
   "cap": "In **2003**, claiming Saddam Hussein held weapons of mass destruction—claims that proved false—the U.S. launched the **Iraq War** without UN approval. Baghdad fell fast and Saddam was toppled, but insurgency and sectarian bloodshed followed, isolating America and drawing comparisons to Vietnam."
  },
  {
   "img": "images/ch28/strip3.jpg",
   "date": "2005",
   "cap": "**Hurricane Katrina** flooded New Orleans in **2005**, displacing most of its largely Black population. The botched federal response discredited the Bush administration's reputation for competence. Courts also checked the president, affirming detainees' rights and, in **Lawrence v. Texas**, signaling the 1960s social revolution was permanent."
  },
  {
   "img": "images/ch28/strip4.jpg",
   "date": "2007–2008",
   "cap": "The housing bubble burst and the **Great Recession** began in December **2007**. In **2008**, subprime lending and unregulated speculation caught up: Lehman Brothers failed and Congress passed a $700 billion **Bank bailout** to rescue firms 'too big to fail'—the worst downturn since the 1930s."
  },
  {
   "img": "images/ch28/strip5.jpg",
   "date": "2008–2009",
   "cap": "In **2008**, **Barack Obama** was elected the first African-American president. In **2009** Congress enacted a nearly $800 billion stimulus and **Sonia Sotomayor** became the first Hispanic Supreme Court justice—but the **Tea Party** movement emerged in backlash against spending and government growth."
  },
  {
   "img": "images/ch28/strip6.jpg",
   "date": "2010",
   "cap": "In **2010**, the **Affordable Care Act** extended health coverage to millions, alongside a sweeping financial-reform law. But the **Tea Party** backlash helped Republicans capture the House that fall, producing years of lasting gridlock between Congress and the president."
  },
  {
   "img": "images/ch28/strip7.jpg",
   "date": "2011–2012",
   "cap": "In **2011**, U.S. forces killed Osama bin Laden and the last troops left Iraq, ending the **Iraq War**; **Occupy Wall Street** protested extreme inequality as the Arab Spring swept the Middle East. In **2012**, Obama won reelection over Mitt Romney, powered by the electorate's growing diversity."
  },
  {
   "img": "images/ch28/strip8.jpg",
   "date": "2013–2015",
   "cap": "In **2013**, **Edward Snowden** exposed mass NSA surveillance as the Court gutted the Voting Rights Act; **Black Lives Matter** confronted police violence while **ISIS** rose in Iraq and Syria. In **2015**, **Obergefell v. Hodges** legalized same-sex marriage nationwide, the U.S. restored relations with Cuba, and joined the global climate agreement."
  }
 ]
};
